using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string AppointmentConfig = @"AppointmentConfig";
        
		public static readonly string TblAbout = @"TblAbout";
        
		public static readonly string TblAdvantage = @"TblAdvantage";
        
		public static readonly string TblAdver = @"TblAdver";
        
		public static readonly string TblAdvertise = @"TblAdvertise";
        
		public static readonly string TblAppointment = @"TblAppointment";
        
		public static readonly string TblBanner = @"TblBanner";
        
		public static readonly string TblBlog = @"TblBlog";
        
		public static readonly string TblBranch = @"TblBranch";
        
		public static readonly string TblCard = @"TblCard";
        
		public static readonly string TblCity = @"TblCity";
        
		public static readonly string TblDoctorImage = @"TblDoctorImage";
        
		public static readonly string TblDoctor = @"TblDoctors";
        
		public static readonly string TblMessage = @"TblMessage";
        
		public static readonly string TblPage = @"TblPage";
        
		public static readonly string TblPicture = @"TblPicture";
        
		public static readonly string TblPlan = @"TblPlan";
        
		public static readonly string TblReserve = @"TblReserve";
        
		public static readonly string TblState = @"TblState";
        
		public static readonly string TblUser = @"TblUser";
        
		public static readonly string TblVideo = @"TblVideo";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table AppointmentConfig
		{
            get { return DataService.GetSchema("AppointmentConfig", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblAbout
		{
            get { return DataService.GetSchema("TblAbout", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblAdvantage
		{
            get { return DataService.GetSchema("TblAdvantage", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblAdver
		{
            get { return DataService.GetSchema("TblAdver", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblAdvertise
		{
            get { return DataService.GetSchema("TblAdvertise", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblAppointment
		{
            get { return DataService.GetSchema("TblAppointment", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblBanner
		{
            get { return DataService.GetSchema("TblBanner", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblBlog
		{
            get { return DataService.GetSchema("TblBlog", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblBranch
		{
            get { return DataService.GetSchema("TblBranch", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblCard
		{
            get { return DataService.GetSchema("TblCard", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblCity
		{
            get { return DataService.GetSchema("TblCity", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblDoctorImage
		{
            get { return DataService.GetSchema("TblDoctorImage", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblDoctor
		{
            get { return DataService.GetSchema("TblDoctors", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblMessage
		{
            get { return DataService.GetSchema("TblMessage", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblPage
		{
            get { return DataService.GetSchema("TblPage", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblPicture
		{
            get { return DataService.GetSchema("TblPicture", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblPlan
		{
            get { return DataService.GetSchema("TblPlan", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblReserve
		{
            get { return DataService.GetSchema("TblReserve", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblState
		{
            get { return DataService.GetSchema("TblState", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblUser
		{
            get { return DataService.GetSchema("TblUser", "DbWebSiteConnectionString"); }
		}
        
		public static TableSchema.Table TblVideo
		{
            get { return DataService.GetSchema("TblVideo", "DbWebSiteConnectionString"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["DbWebSiteConnectionString"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	}
    #endregion
    
}
#region Databases
public partial struct Databases 
{
	
	public static readonly string DbWebSiteConnectionString = @"DbWebSiteConnectionString";
    
}
#endregion