using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the AppointmentConfig class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class AppointmentConfigCollection : ActiveList<AppointmentConfig, AppointmentConfigCollection>
	{	   
		public AppointmentConfigCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>AppointmentConfigCollection</returns>
		public AppointmentConfigCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                AppointmentConfig o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the AppointmentConfig table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class AppointmentConfig : ActiveRecord<AppointmentConfig>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public AppointmentConfig()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public AppointmentConfig(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public AppointmentConfig(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public AppointmentConfig(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("AppointmentConfig", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarDoctorId = new TableSchema.TableColumn(schema);
				colvarDoctorId.ColumnName = "doctorId";
				colvarDoctorId.DataType = DbType.Int32;
				colvarDoctorId.MaxLength = 0;
				colvarDoctorId.AutoIncrement = false;
				colvarDoctorId.IsNullable = false;
				colvarDoctorId.IsPrimaryKey = false;
				colvarDoctorId.IsForeignKey = false;
				colvarDoctorId.IsReadOnly = false;
				colvarDoctorId.DefaultSetting = @"";
				colvarDoctorId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDoctorId);
				
				TableSchema.TableColumn colvarDay = new TableSchema.TableColumn(schema);
				colvarDay.ColumnName = "day";
				colvarDay.DataType = DbType.Int32;
				colvarDay.MaxLength = 0;
				colvarDay.AutoIncrement = false;
				colvarDay.IsNullable = true;
				colvarDay.IsPrimaryKey = false;
				colvarDay.IsForeignKey = false;
				colvarDay.IsReadOnly = false;
				colvarDay.DefaultSetting = @"";
				colvarDay.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDay);
				
				TableSchema.TableColumn colvarShift = new TableSchema.TableColumn(schema);
				colvarShift.ColumnName = "shift";
				colvarShift.DataType = DbType.Int32;
				colvarShift.MaxLength = 0;
				colvarShift.AutoIncrement = false;
				colvarShift.IsNullable = true;
				colvarShift.IsPrimaryKey = false;
				colvarShift.IsForeignKey = false;
				colvarShift.IsReadOnly = false;
				colvarShift.DefaultSetting = @"";
				colvarShift.ForeignKeyTableName = "";
				schema.Columns.Add(colvarShift);
				
				TableSchema.TableColumn colvarStartTime = new TableSchema.TableColumn(schema);
				colvarStartTime.ColumnName = "startTime";
				colvarStartTime.DataType = DbType.AnsiString;
				colvarStartTime.MaxLength = 0;
				colvarStartTime.AutoIncrement = false;
				colvarStartTime.IsNullable = true;
				colvarStartTime.IsPrimaryKey = false;
				colvarStartTime.IsForeignKey = false;
				colvarStartTime.IsReadOnly = false;
				colvarStartTime.DefaultSetting = @"";
				colvarStartTime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStartTime);
				
				TableSchema.TableColumn colvarGap = new TableSchema.TableColumn(schema);
				colvarGap.ColumnName = "gap";
				colvarGap.DataType = DbType.Int32;
				colvarGap.MaxLength = 0;
				colvarGap.AutoIncrement = false;
				colvarGap.IsNullable = true;
				colvarGap.IsPrimaryKey = false;
				colvarGap.IsForeignKey = false;
				colvarGap.IsReadOnly = false;
				colvarGap.DefaultSetting = @"";
				colvarGap.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGap);
				
				TableSchema.TableColumn colvarNumber = new TableSchema.TableColumn(schema);
				colvarNumber.ColumnName = "number";
				colvarNumber.DataType = DbType.Int32;
				colvarNumber.MaxLength = 0;
				colvarNumber.AutoIncrement = false;
				colvarNumber.IsNullable = true;
				colvarNumber.IsPrimaryKey = false;
				colvarNumber.IsForeignKey = false;
				colvarNumber.IsReadOnly = false;
				colvarNumber.DefaultSetting = @"";
				colvarNumber.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNumber);
				
				TableSchema.TableColumn colvarTime = new TableSchema.TableColumn(schema);
				colvarTime.ColumnName = "time";
				colvarTime.DataType = DbType.Int32;
				colvarTime.MaxLength = 0;
				colvarTime.AutoIncrement = false;
				colvarTime.IsNullable = true;
				colvarTime.IsPrimaryKey = false;
				colvarTime.IsForeignKey = false;
				colvarTime.IsReadOnly = false;
				colvarTime.DefaultSetting = @"";
				colvarTime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTime);
				
				TableSchema.TableColumn colvarCode = new TableSchema.TableColumn(schema);
				colvarCode.ColumnName = "code";
				colvarCode.DataType = DbType.String;
				colvarCode.MaxLength = 30;
				colvarCode.AutoIncrement = false;
				colvarCode.IsNullable = true;
				colvarCode.IsPrimaryKey = false;
				colvarCode.IsForeignKey = false;
				colvarCode.IsReadOnly = false;
				colvarCode.DefaultSetting = @"";
				colvarCode.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCode);
				
				TableSchema.TableColumn colvarActive = new TableSchema.TableColumn(schema);
				colvarActive.ColumnName = "active";
				colvarActive.DataType = DbType.Byte;
				colvarActive.MaxLength = 0;
				colvarActive.AutoIncrement = false;
				colvarActive.IsNullable = true;
				colvarActive.IsPrimaryKey = false;
				colvarActive.IsForeignKey = false;
				colvarActive.IsReadOnly = false;
				colvarActive.DefaultSetting = @"";
				colvarActive.ForeignKeyTableName = "";
				schema.Columns.Add(colvarActive);
				
				TableSchema.TableColumn colvarSaveDate = new TableSchema.TableColumn(schema);
				colvarSaveDate.ColumnName = "saveDate";
				colvarSaveDate.DataType = DbType.DateTime;
				colvarSaveDate.MaxLength = 0;
				colvarSaveDate.AutoIncrement = false;
				colvarSaveDate.IsNullable = true;
				colvarSaveDate.IsPrimaryKey = false;
				colvarSaveDate.IsForeignKey = false;
				colvarSaveDate.IsReadOnly = false;
				colvarSaveDate.DefaultSetting = @"";
				colvarSaveDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSaveDate);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("AppointmentConfig",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("DoctorId")]
		[Bindable(true)]
        [DataMember]
		public int DoctorId 
		{
			get { return GetColumnValue<int>(Columns.DoctorId); }
			set { SetColumnValue(Columns.DoctorId, value); }
		}
		  
		[XmlAttribute("Day")]
		[Bindable(true)]
        [DataMember]
		public int? Day 
		{
			get { return GetColumnValue<int?>(Columns.Day); }
			set { SetColumnValue(Columns.Day, value); }
		}
		  
		[XmlAttribute("Shift")]
		[Bindable(true)]
        [DataMember]
		public int? Shift 
		{
			get { return GetColumnValue<int?>(Columns.Shift); }
			set { SetColumnValue(Columns.Shift, value); }
		}
		  
		[XmlAttribute("StartTime")]
		[Bindable(true)]
        [DataMember]
		public string StartTime 
		{
			get { return GetColumnValue<string>(Columns.StartTime); }
			set { SetColumnValue(Columns.StartTime, value); }
		}
		  
		[XmlAttribute("Gap")]
		[Bindable(true)]
        [DataMember]
		public int? Gap 
		{
			get { return GetColumnValue<int?>(Columns.Gap); }
			set { SetColumnValue(Columns.Gap, value); }
		}
		  
		[XmlAttribute("Number")]
		[Bindable(true)]
        [DataMember]
		public int? Number 
		{
			get { return GetColumnValue<int?>(Columns.Number); }
			set { SetColumnValue(Columns.Number, value); }
		}
		  
		[XmlAttribute("Time")]
		[Bindable(true)]
        [DataMember]
		public int? Time 
		{
			get { return GetColumnValue<int?>(Columns.Time); }
			set { SetColumnValue(Columns.Time, value); }
		}
		  
		[XmlAttribute("Code")]
		[Bindable(true)]
        [DataMember]
		public string Code 
		{
			get { return GetColumnValue<string>(Columns.Code); }
			set { SetColumnValue(Columns.Code, value); }
		}
		  
		[XmlAttribute("Active")]
		[Bindable(true)]
        [DataMember]
		public byte? Active 
		{
			get { return GetColumnValue<byte?>(Columns.Active); }
			set { SetColumnValue(Columns.Active, value); }
		}
		  
		[XmlAttribute("SaveDate")]
		[Bindable(true)]
        [DataMember]
		public DateTime? SaveDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.SaveDate); }
			set { SetColumnValue(Columns.SaveDate, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varDoctorId,int? varDay,int? varShift,string varStartTime,int? varGap,int? varNumber,int? varTime,string varCode,byte? varActive,DateTime? varSaveDate)
		{
			AppointmentConfig item = new AppointmentConfig();
			
			item.DoctorId = varDoctorId;
			
			item.Day = varDay;
			
			item.Shift = varShift;
			
			item.StartTime = varStartTime;
			
			item.Gap = varGap;
			
			item.Number = varNumber;
			
			item.Time = varTime;
			
			item.Code = varCode;
			
			item.Active = varActive;
			
			item.SaveDate = varSaveDate;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int varDoctorId,int? varDay,int? varShift,string varStartTime,int? varGap,int? varNumber,int? varTime,string varCode,byte? varActive,DateTime? varSaveDate)
		{
			AppointmentConfig item = new AppointmentConfig();
			
				item.Id = varId;
			
				item.DoctorId = varDoctorId;
			
				item.Day = varDay;
			
				item.Shift = varShift;
			
				item.StartTime = varStartTime;
			
				item.Gap = varGap;
			
				item.Number = varNumber;
			
				item.Time = varTime;
			
				item.Code = varCode;
			
				item.Active = varActive;
			
				item.SaveDate = varSaveDate;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn DoctorIdColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn DayColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ShiftColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn StartTimeColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn GapColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn NumberColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn TimeColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn CodeColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn ActiveColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn SaveDateColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string DoctorId = @"doctorId";
			 public static string Day = @"day";
			 public static string Shift = @"shift";
			 public static string StartTime = @"startTime";
			 public static string Gap = @"gap";
			 public static string Number = @"number";
			 public static string Time = @"time";
			 public static string Code = @"code";
			 public static string Active = @"active";
			 public static string SaveDate = @"saveDate";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
