using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite{
    public partial class SPs{
        
        /// <summary>
        /// Creates an object wrapper for the admin_selectCity Procedure
        /// </summary>
        public static StoredProcedure AdminSelectCity()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("admin_selectCity", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the deleteCity Procedure
        /// </summary>
        public static StoredProcedure DeleteCity(int? cityId)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("deleteCity", DataService.GetInstance("DbWebSiteConnectionString"), "bartar_user");
        	
            sp.Command.AddParameter("@cityId", cityId, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the insertApointment Procedure
        /// </summary>
        public static StoredProcedure InsertApointment(int? doctorId, int? num, int? shift, string startTime, int? time, string dateX)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("insertApointment", DataService.GetInstance("DbWebSiteConnectionString"), "doctorya_user");
        	
            sp.Command.AddParameter("@doctorId", doctorId, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@num", num, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@shift", shift, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@startTime", startTime, DbType.AnsiString, null, null);
        	
            sp.Command.AddParameter("@time", time, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@date", dateX, DbType.AnsiString, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the insertCity Procedure
        /// </summary>
        public static StoredProcedure InsertCity(string name)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("insertCity", DataService.GetInstance("DbWebSiteConnectionString"), "bartar_user");
        	
            sp.Command.AddParameter("@name", name, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the panel_deleteAppointment Procedure
        /// </summary>
        public static StoredProcedure PanelDeleteAppointment(int? doctorId, string groupCode)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("panel_deleteAppointment", DataService.GetInstance("DbWebSiteConnectionString"), "doctorya_user");
        	
            sp.Command.AddParameter("@doctorId", doctorId, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@groupCode", groupCode, DbType.AnsiString, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the panel_selectAppointment Procedure
        /// </summary>
        public static StoredProcedure PanelSelectAppointment(int? doctorId)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("panel_selectAppointment", DataService.GetInstance("DbWebSiteConnectionString"), "doctorya_user");
        	
            sp.Command.AddParameter("@doctorId", doctorId, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the panel_selectAppointment_detail Procedure
        /// </summary>
        public static StoredProcedure PanelSelectAppointmentDetail(int? appointmentId)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("panel_selectAppointment_detail", DataService.GetInstance("DbWebSiteConnectionString"), "doctorya_user");
        	
            sp.Command.AddParameter("@appointmentId", appointmentId, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the panel_selectAppointment_v1 Procedure
        /// </summary>
        public static StoredProcedure PanelSelectAppointmentV1(int? doctorId)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("panel_selectAppointment_v1", DataService.GetInstance("DbWebSiteConnectionString"), "doctorya_user");
        	
            sp.Command.AddParameter("@doctorId", doctorId, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the panel_selectAppointmentDetail Procedure
        /// </summary>
        public static StoredProcedure PanelSelectAppointmentDetail(string groupCode)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("panel_selectAppointmentDetail", DataService.GetInstance("DbWebSiteConnectionString"), "doctorya_user");
        	
            sp.Command.AddParameter("@groupCode", groupCode, DbType.AnsiString, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the panel_selectReserves Procedure
        /// </summary>
        public static StoredProcedure PanelSelectReserves(int? doctorId)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("panel_selectReserves", DataService.GetInstance("DbWebSiteConnectionString"), "doctorya_user");
        	
            sp.Command.AddParameter("@doctorId", doctorId, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectAppointment Procedure
        /// </summary>
        public static StoredProcedure SelectAppointment(int? doctorId)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectAppointment", DataService.GetInstance("DbWebSiteConnectionString"), "doctorya_user");
        	
            sp.Command.AddParameter("@doctorId", doctorId, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectAppointment_v1 Procedure
        /// </summary>
        public static StoredProcedure SelectAppointmentV1(int? doctorId)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectAppointment_v1", DataService.GetInstance("DbWebSiteConnectionString"), "dbo");
        	
            sp.Command.AddParameter("@doctorId", doctorId, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectAppointmentDetail Procedure
        /// </summary>
        public static StoredProcedure SelectAppointmentDetail(int? id)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectAppointmentDetail", DataService.GetInstance("DbWebSiteConnectionString"), "doctorya_user");
        	
            sp.Command.AddParameter("@id", id, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectArabicDoctorBreadcrumb Procedure
        /// </summary>
        public static StoredProcedure SelectArabicDoctorBreadcrumb(int? city, int? branch, string name)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectArabicDoctorBreadcrumb", DataService.GetInstance("DbWebSiteConnectionString"), "dbo");
        	
            sp.Command.AddParameter("@city", city, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@branch", branch, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@name", name, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectArabicDoctors Procedure
        /// </summary>
        public static StoredProcedure SelectArabicDoctors(int? city, int? branch, string name)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectArabicDoctors", DataService.GetInstance("DbWebSiteConnectionString"), "dbo");
        	
            sp.Command.AddParameter("@city", city, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@branch", branch, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@name", name, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectArBanners Procedure
        /// </summary>
        public static StoredProcedure SelectArBanners()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectArBanners", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectArTopBanner Procedure
        /// </summary>
        public static StoredProcedure SelectArTopBanner()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectArTopBanner", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectBanners Procedure
        /// </summary>
        public static StoredProcedure SelectBanners()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectBanners", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectBlog Procedure
        /// </summary>
        public static StoredProcedure SelectBlog()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectBlog", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectBlogTags Procedure
        /// </summary>
        public static StoredProcedure SelectBlogTags(int? id)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectBlogTags", DataService.GetInstance("DbWebSiteConnectionString"), "dbo");
        	
            sp.Command.AddParameter("@id", id, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectCity Procedure
        /// </summary>
        public static StoredProcedure SelectCity()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectCity", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectDoctorBreadcrumb Procedure
        /// </summary>
        public static StoredProcedure SelectDoctorBreadcrumb(int? city, int? branch, string name)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectDoctorBreadcrumb", DataService.GetInstance("DbWebSiteConnectionString"), "dbo");
        	
            sp.Command.AddParameter("@city", city, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@branch", branch, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@name", name, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectDoctorDetail Procedure
        /// </summary>
        public static StoredProcedure SelectDoctorDetail(int? id)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectDoctorDetail", DataService.GetInstance("DbWebSiteConnectionString"), "dbo");
        	
            sp.Command.AddParameter("@id", id, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectDoctors Procedure
        /// </summary>
        public static StoredProcedure SelectDoctors(int? city, int? branch, string name)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectDoctors", DataService.GetInstance("DbWebSiteConnectionString"), "dbo");
        	
            sp.Command.AddParameter("@city", city, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@branch", branch, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@name", name, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectEnBanners Procedure
        /// </summary>
        public static StoredProcedure SelectEnBanners()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectEnBanners", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectEnglishDoctorBreadcrumb Procedure
        /// </summary>
        public static StoredProcedure SelectEnglishDoctorBreadcrumb(int? city, int? branch, string name)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectEnglishDoctorBreadcrumb", DataService.GetInstance("DbWebSiteConnectionString"), "dbo");
        	
            sp.Command.AddParameter("@city", city, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@branch", branch, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@name", name, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectEnglishDoctors Procedure
        /// </summary>
        public static StoredProcedure SelectEnglishDoctors(int? city, int? branch, string name)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectEnglishDoctors", DataService.GetInstance("DbWebSiteConnectionString"), "dbo");
        	
            sp.Command.AddParameter("@city", city, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@branch", branch, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@name", name, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectEnTopBanner Procedure
        /// </summary>
        public static StoredProcedure SelectEnTopBanner()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectEnTopBanner", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectLastArabicSpecialDoctors Procedure
        /// </summary>
        public static StoredProcedure SelectLastArabicSpecialDoctors()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectLastArabicSpecialDoctors", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectLastBlog Procedure
        /// </summary>
        public static StoredProcedure SelectLastBlog()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectLastBlog", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectLastDoctors Procedure
        /// </summary>
        public static StoredProcedure SelectLastDoctors(int? city)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectLastDoctors", DataService.GetInstance("DbWebSiteConnectionString"), "bartar_user");
        	
            sp.Command.AddParameter("@city", city, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectLastEnglishSpecialDoctors Procedure
        /// </summary>
        public static StoredProcedure SelectLastEnglishSpecialDoctors()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectLastEnglishSpecialDoctors", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectLastSpecialDoctors Procedure
        /// </summary>
        public static StoredProcedure SelectLastSpecialDoctors()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectLastSpecialDoctors", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectSomeBranch Procedure
        /// </summary>
        public static StoredProcedure SelectSomeBranch()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectSomeBranch", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectSummery Procedure
        /// </summary>
        public static StoredProcedure SelectSummery()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectSummery", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the selectTopBanner Procedure
        /// </summary>
        public static StoredProcedure SelectTopBanner()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("selectTopBanner", DataService.GetInstance("DbWebSiteConnectionString"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the updateCity Procedure
        /// </summary>
        public static StoredProcedure UpdateCity(int? cityId, string name)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("updateCity", DataService.GetInstance("DbWebSiteConnectionString"), "bartar_user");
        	
            sp.Command.AddParameter("@cityId", cityId, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@name", name, DbType.String, null, null);
        	
            return sp;
        }
        
    }
    
}
