using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblAdver class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblAdverCollection : ActiveList<TblAdver, TblAdverCollection>
	{	   
		public TblAdverCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblAdverCollection</returns>
		public TblAdverCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblAdver o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblAdver table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblAdver : ActiveRecord<TblAdver>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblAdver()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblAdver(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblAdver(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblAdver(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblAdver", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarASubject = new TableSchema.TableColumn(schema);
				colvarASubject.ColumnName = "aSubject";
				colvarASubject.DataType = DbType.String;
				colvarASubject.MaxLength = 50;
				colvarASubject.AutoIncrement = false;
				colvarASubject.IsNullable = true;
				colvarASubject.IsPrimaryKey = false;
				colvarASubject.IsForeignKey = false;
				colvarASubject.IsReadOnly = false;
				colvarASubject.DefaultSetting = @"";
				colvarASubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarASubject);
				
				TableSchema.TableColumn colvarAImage = new TableSchema.TableColumn(schema);
				colvarAImage.ColumnName = "aImage";
				colvarAImage.DataType = DbType.String;
				colvarAImage.MaxLength = 250;
				colvarAImage.AutoIncrement = false;
				colvarAImage.IsNullable = true;
				colvarAImage.IsPrimaryKey = false;
				colvarAImage.IsForeignKey = false;
				colvarAImage.IsReadOnly = false;
				colvarAImage.DefaultSetting = @"";
				colvarAImage.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAImage);
				
				TableSchema.TableColumn colvarALink = new TableSchema.TableColumn(schema);
				colvarALink.ColumnName = "aLink";
				colvarALink.DataType = DbType.String;
				colvarALink.MaxLength = 500;
				colvarALink.AutoIncrement = false;
				colvarALink.IsNullable = true;
				colvarALink.IsPrimaryKey = false;
				colvarALink.IsForeignKey = false;
				colvarALink.IsReadOnly = false;
				colvarALink.DefaultSetting = @"";
				colvarALink.ForeignKeyTableName = "";
				schema.Columns.Add(colvarALink);
				
				TableSchema.TableColumn colvarAStatus = new TableSchema.TableColumn(schema);
				colvarAStatus.ColumnName = "aStatus";
				colvarAStatus.DataType = DbType.Boolean;
				colvarAStatus.MaxLength = 0;
				colvarAStatus.AutoIncrement = false;
				colvarAStatus.IsNullable = true;
				colvarAStatus.IsPrimaryKey = false;
				colvarAStatus.IsForeignKey = false;
				colvarAStatus.IsReadOnly = false;
				colvarAStatus.DefaultSetting = @"";
				colvarAStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAStatus);
				
				TableSchema.TableColumn colvarAStateFk = new TableSchema.TableColumn(schema);
				colvarAStateFk.ColumnName = "aStateFk";
				colvarAStateFk.DataType = DbType.Int32;
				colvarAStateFk.MaxLength = 0;
				colvarAStateFk.AutoIncrement = false;
				colvarAStateFk.IsNullable = true;
				colvarAStateFk.IsPrimaryKey = false;
				colvarAStateFk.IsForeignKey = false;
				colvarAStateFk.IsReadOnly = false;
				colvarAStateFk.DefaultSetting = @"";
				colvarAStateFk.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAStateFk);
				
				TableSchema.TableColumn colvarALanguage = new TableSchema.TableColumn(schema);
				colvarALanguage.ColumnName = "aLanguage";
				colvarALanguage.DataType = DbType.Byte;
				colvarALanguage.MaxLength = 0;
				colvarALanguage.AutoIncrement = false;
				colvarALanguage.IsNullable = true;
				colvarALanguage.IsPrimaryKey = false;
				colvarALanguage.IsForeignKey = false;
				colvarALanguage.IsReadOnly = false;
				colvarALanguage.DefaultSetting = @"";
				colvarALanguage.ForeignKeyTableName = "";
				schema.Columns.Add(colvarALanguage);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblAdver",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("ASubject")]
		[Bindable(true)]
        [DataMember]
		public string ASubject 
		{
			get { return GetColumnValue<string>(Columns.ASubject); }
			set { SetColumnValue(Columns.ASubject, value); }
		}
		  
		[XmlAttribute("AImage")]
		[Bindable(true)]
        [DataMember]
		public string AImage 
		{
			get { return GetColumnValue<string>(Columns.AImage); }
			set { SetColumnValue(Columns.AImage, value); }
		}
		  
		[XmlAttribute("ALink")]
		[Bindable(true)]
        [DataMember]
		public string ALink 
		{
			get { return GetColumnValue<string>(Columns.ALink); }
			set { SetColumnValue(Columns.ALink, value); }
		}
		  
		[XmlAttribute("AStatus")]
		[Bindable(true)]
        [DataMember]
		public bool? AStatus 
		{
			get { return GetColumnValue<bool?>(Columns.AStatus); }
			set { SetColumnValue(Columns.AStatus, value); }
		}
		  
		[XmlAttribute("AStateFk")]
		[Bindable(true)]
        [DataMember]
		public int? AStateFk 
		{
			get { return GetColumnValue<int?>(Columns.AStateFk); }
			set { SetColumnValue(Columns.AStateFk, value); }
		}
		  
		[XmlAttribute("ALanguage")]
		[Bindable(true)]
        [DataMember]
		public byte? ALanguage 
		{
			get { return GetColumnValue<byte?>(Columns.ALanguage); }
			set { SetColumnValue(Columns.ALanguage, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varASubject,string varAImage,string varALink,bool? varAStatus,int? varAStateFk,byte? varALanguage)
		{
			TblAdver item = new TblAdver();
			
			item.ASubject = varASubject;
			
			item.AImage = varAImage;
			
			item.ALink = varALink;
			
			item.AStatus = varAStatus;
			
			item.AStateFk = varAStateFk;
			
			item.ALanguage = varALanguage;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varASubject,string varAImage,string varALink,bool? varAStatus,int? varAStateFk,byte? varALanguage)
		{
			TblAdver item = new TblAdver();
			
				item.Id = varId;
			
				item.ASubject = varASubject;
			
				item.AImage = varAImage;
			
				item.ALink = varALink;
			
				item.AStatus = varAStatus;
			
				item.AStateFk = varAStateFk;
			
				item.ALanguage = varALanguage;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ASubjectColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn AImageColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ALinkColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn AStatusColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn AStateFkColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn ALanguageColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string ASubject = @"aSubject";
			 public static string AImage = @"aImage";
			 public static string ALink = @"aLink";
			 public static string AStatus = @"aStatus";
			 public static string AStateFk = @"aStateFk";
			 public static string ALanguage = @"aLanguage";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
