using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblAbout class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblAboutCollection : ActiveList<TblAbout, TblAboutCollection>
	{	   
		public TblAboutCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblAboutCollection</returns>
		public TblAboutCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblAbout o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblAbout table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblAbout : ActiveRecord<TblAbout>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblAbout()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblAbout(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblAbout(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblAbout(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblAbout", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarADescription = new TableSchema.TableColumn(schema);
				colvarADescription.ColumnName = "aDescription";
				colvarADescription.DataType = DbType.String;
				colvarADescription.MaxLength = -1;
				colvarADescription.AutoIncrement = false;
				colvarADescription.IsNullable = true;
				colvarADescription.IsPrimaryKey = false;
				colvarADescription.IsForeignKey = false;
				colvarADescription.IsReadOnly = false;
				colvarADescription.DefaultSetting = @"";
				colvarADescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarADescription);
				
				TableSchema.TableColumn colvarATel = new TableSchema.TableColumn(schema);
				colvarATel.ColumnName = "aTel";
				colvarATel.DataType = DbType.String;
				colvarATel.MaxLength = 30;
				colvarATel.AutoIncrement = false;
				colvarATel.IsNullable = true;
				colvarATel.IsPrimaryKey = false;
				colvarATel.IsForeignKey = false;
				colvarATel.IsReadOnly = false;
				colvarATel.DefaultSetting = @"";
				colvarATel.ForeignKeyTableName = "";
				schema.Columns.Add(colvarATel);
				
				TableSchema.TableColumn colvarAMobile = new TableSchema.TableColumn(schema);
				colvarAMobile.ColumnName = "aMobile";
				colvarAMobile.DataType = DbType.String;
				colvarAMobile.MaxLength = 30;
				colvarAMobile.AutoIncrement = false;
				colvarAMobile.IsNullable = true;
				colvarAMobile.IsPrimaryKey = false;
				colvarAMobile.IsForeignKey = false;
				colvarAMobile.IsReadOnly = false;
				colvarAMobile.DefaultSetting = @"";
				colvarAMobile.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAMobile);
				
				TableSchema.TableColumn colvarAEmail = new TableSchema.TableColumn(schema);
				colvarAEmail.ColumnName = "aEmail";
				colvarAEmail.DataType = DbType.String;
				colvarAEmail.MaxLength = 50;
				colvarAEmail.AutoIncrement = false;
				colvarAEmail.IsNullable = true;
				colvarAEmail.IsPrimaryKey = false;
				colvarAEmail.IsForeignKey = false;
				colvarAEmail.IsReadOnly = false;
				colvarAEmail.DefaultSetting = @"";
				colvarAEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAEmail);
				
				TableSchema.TableColumn colvarATelegram = new TableSchema.TableColumn(schema);
				colvarATelegram.ColumnName = "aTelegram";
				colvarATelegram.DataType = DbType.String;
				colvarATelegram.MaxLength = 50;
				colvarATelegram.AutoIncrement = false;
				colvarATelegram.IsNullable = true;
				colvarATelegram.IsPrimaryKey = false;
				colvarATelegram.IsForeignKey = false;
				colvarATelegram.IsReadOnly = false;
				colvarATelegram.DefaultSetting = @"";
				colvarATelegram.ForeignKeyTableName = "";
				schema.Columns.Add(colvarATelegram);
				
				TableSchema.TableColumn colvarAInstagram = new TableSchema.TableColumn(schema);
				colvarAInstagram.ColumnName = "aInstagram";
				colvarAInstagram.DataType = DbType.String;
				colvarAInstagram.MaxLength = 50;
				colvarAInstagram.AutoIncrement = false;
				colvarAInstagram.IsNullable = true;
				colvarAInstagram.IsPrimaryKey = false;
				colvarAInstagram.IsForeignKey = false;
				colvarAInstagram.IsReadOnly = false;
				colvarAInstagram.DefaultSetting = @"";
				colvarAInstagram.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAInstagram);
				
				TableSchema.TableColumn colvarAAparat = new TableSchema.TableColumn(schema);
				colvarAAparat.ColumnName = "aAparat";
				colvarAAparat.DataType = DbType.String;
				colvarAAparat.MaxLength = 50;
				colvarAAparat.AutoIncrement = false;
				colvarAAparat.IsNullable = true;
				colvarAAparat.IsPrimaryKey = false;
				colvarAAparat.IsForeignKey = false;
				colvarAAparat.IsReadOnly = false;
				colvarAAparat.DefaultSetting = @"";
				colvarAAparat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAAparat);
				
				TableSchema.TableColumn colvarAImg1 = new TableSchema.TableColumn(schema);
				colvarAImg1.ColumnName = "aImg1";
				colvarAImg1.DataType = DbType.String;
				colvarAImg1.MaxLength = 250;
				colvarAImg1.AutoIncrement = false;
				colvarAImg1.IsNullable = true;
				colvarAImg1.IsPrimaryKey = false;
				colvarAImg1.IsForeignKey = false;
				colvarAImg1.IsReadOnly = false;
				colvarAImg1.DefaultSetting = @"";
				colvarAImg1.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAImg1);
				
				TableSchema.TableColumn colvarAImg2 = new TableSchema.TableColumn(schema);
				colvarAImg2.ColumnName = "aImg2";
				colvarAImg2.DataType = DbType.String;
				colvarAImg2.MaxLength = 250;
				colvarAImg2.AutoIncrement = false;
				colvarAImg2.IsNullable = true;
				colvarAImg2.IsPrimaryKey = false;
				colvarAImg2.IsForeignKey = false;
				colvarAImg2.IsReadOnly = false;
				colvarAImg2.DefaultSetting = @"";
				colvarAImg2.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAImg2);
				
				TableSchema.TableColumn colvarAWhatsapp = new TableSchema.TableColumn(schema);
				colvarAWhatsapp.ColumnName = "aWhatsapp";
				colvarAWhatsapp.DataType = DbType.String;
				colvarAWhatsapp.MaxLength = 30;
				colvarAWhatsapp.AutoIncrement = false;
				colvarAWhatsapp.IsNullable = true;
				colvarAWhatsapp.IsPrimaryKey = false;
				colvarAWhatsapp.IsForeignKey = false;
				colvarAWhatsapp.IsReadOnly = false;
				colvarAWhatsapp.DefaultSetting = @"";
				colvarAWhatsapp.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAWhatsapp);
				
				TableSchema.TableColumn colvarLastDoctorType = new TableSchema.TableColumn(schema);
				colvarLastDoctorType.ColumnName = "lastDoctorType";
				colvarLastDoctorType.DataType = DbType.Byte;
				colvarLastDoctorType.MaxLength = 0;
				colvarLastDoctorType.AutoIncrement = false;
				colvarLastDoctorType.IsNullable = true;
				colvarLastDoctorType.IsPrimaryKey = false;
				colvarLastDoctorType.IsForeignKey = false;
				colvarLastDoctorType.IsReadOnly = false;
				colvarLastDoctorType.DefaultSetting = @"";
				colvarLastDoctorType.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLastDoctorType);
				
				TableSchema.TableColumn colvarAFooterText = new TableSchema.TableColumn(schema);
				colvarAFooterText.ColumnName = "aFooterText";
				colvarAFooterText.DataType = DbType.String;
				colvarAFooterText.MaxLength = 500;
				colvarAFooterText.AutoIncrement = false;
				colvarAFooterText.IsNullable = true;
				colvarAFooterText.IsPrimaryKey = false;
				colvarAFooterText.IsForeignKey = false;
				colvarAFooterText.IsReadOnly = false;
				colvarAFooterText.DefaultSetting = @"";
				colvarAFooterText.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAFooterText);
				
				TableSchema.TableColumn colvarAAddress = new TableSchema.TableColumn(schema);
				colvarAAddress.ColumnName = "aAddress";
				colvarAAddress.DataType = DbType.String;
				colvarAAddress.MaxLength = 300;
				colvarAAddress.AutoIncrement = false;
				colvarAAddress.IsNullable = true;
				colvarAAddress.IsPrimaryKey = false;
				colvarAAddress.IsForeignKey = false;
				colvarAAddress.IsReadOnly = false;
				colvarAAddress.DefaultSetting = @"";
				colvarAAddress.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAAddress);
				
				TableSchema.TableColumn colvarAArDescription = new TableSchema.TableColumn(schema);
				colvarAArDescription.ColumnName = "aArDescription";
				colvarAArDescription.DataType = DbType.String;
				colvarAArDescription.MaxLength = 4000;
				colvarAArDescription.AutoIncrement = false;
				colvarAArDescription.IsNullable = true;
				colvarAArDescription.IsPrimaryKey = false;
				colvarAArDescription.IsForeignKey = false;
				colvarAArDescription.IsReadOnly = false;
				colvarAArDescription.DefaultSetting = @"";
				colvarAArDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAArDescription);
				
				TableSchema.TableColumn colvarAEnDescription = new TableSchema.TableColumn(schema);
				colvarAEnDescription.ColumnName = "aEnDescription";
				colvarAEnDescription.DataType = DbType.String;
				colvarAEnDescription.MaxLength = 4000;
				colvarAEnDescription.AutoIncrement = false;
				colvarAEnDescription.IsNullable = true;
				colvarAEnDescription.IsPrimaryKey = false;
				colvarAEnDescription.IsForeignKey = false;
				colvarAEnDescription.IsReadOnly = false;
				colvarAEnDescription.DefaultSetting = @"";
				colvarAEnDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAEnDescription);
				
				TableSchema.TableColumn colvarAArAddress = new TableSchema.TableColumn(schema);
				colvarAArAddress.ColumnName = "aArAddress";
				colvarAArAddress.DataType = DbType.String;
				colvarAArAddress.MaxLength = 250;
				colvarAArAddress.AutoIncrement = false;
				colvarAArAddress.IsNullable = true;
				colvarAArAddress.IsPrimaryKey = false;
				colvarAArAddress.IsForeignKey = false;
				colvarAArAddress.IsReadOnly = false;
				colvarAArAddress.DefaultSetting = @"";
				colvarAArAddress.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAArAddress);
				
				TableSchema.TableColumn colvarAEnAddress = new TableSchema.TableColumn(schema);
				colvarAEnAddress.ColumnName = "aEnAddress";
				colvarAEnAddress.DataType = DbType.String;
				colvarAEnAddress.MaxLength = 250;
				colvarAEnAddress.AutoIncrement = false;
				colvarAEnAddress.IsNullable = true;
				colvarAEnAddress.IsPrimaryKey = false;
				colvarAEnAddress.IsForeignKey = false;
				colvarAEnAddress.IsReadOnly = false;
				colvarAEnAddress.DefaultSetting = @"";
				colvarAEnAddress.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAEnAddress);
				
				TableSchema.TableColumn colvarAArFooterText = new TableSchema.TableColumn(schema);
				colvarAArFooterText.ColumnName = "aArFooterText";
				colvarAArFooterText.DataType = DbType.String;
				colvarAArFooterText.MaxLength = 300;
				colvarAArFooterText.AutoIncrement = false;
				colvarAArFooterText.IsNullable = true;
				colvarAArFooterText.IsPrimaryKey = false;
				colvarAArFooterText.IsForeignKey = false;
				colvarAArFooterText.IsReadOnly = false;
				colvarAArFooterText.DefaultSetting = @"";
				colvarAArFooterText.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAArFooterText);
				
				TableSchema.TableColumn colvarAEnFooterText = new TableSchema.TableColumn(schema);
				colvarAEnFooterText.ColumnName = "aEnFooterText";
				colvarAEnFooterText.DataType = DbType.String;
				colvarAEnFooterText.MaxLength = 300;
				colvarAEnFooterText.AutoIncrement = false;
				colvarAEnFooterText.IsNullable = true;
				colvarAEnFooterText.IsPrimaryKey = false;
				colvarAEnFooterText.IsForeignKey = false;
				colvarAEnFooterText.IsReadOnly = false;
				colvarAEnFooterText.DefaultSetting = @"";
				colvarAEnFooterText.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAEnFooterText);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblAbout",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("ADescription")]
		[Bindable(true)]
        [DataMember]
		public string ADescription 
		{
			get { return GetColumnValue<string>(Columns.ADescription); }
			set { SetColumnValue(Columns.ADescription, value); }
		}
		  
		[XmlAttribute("ATel")]
		[Bindable(true)]
        [DataMember]
		public string ATel 
		{
			get { return GetColumnValue<string>(Columns.ATel); }
			set { SetColumnValue(Columns.ATel, value); }
		}
		  
		[XmlAttribute("AMobile")]
		[Bindable(true)]
        [DataMember]
		public string AMobile 
		{
			get { return GetColumnValue<string>(Columns.AMobile); }
			set { SetColumnValue(Columns.AMobile, value); }
		}
		  
		[XmlAttribute("AEmail")]
		[Bindable(true)]
        [DataMember]
		public string AEmail 
		{
			get { return GetColumnValue<string>(Columns.AEmail); }
			set { SetColumnValue(Columns.AEmail, value); }
		}
		  
		[XmlAttribute("ATelegram")]
		[Bindable(true)]
        [DataMember]
		public string ATelegram 
		{
			get { return GetColumnValue<string>(Columns.ATelegram); }
			set { SetColumnValue(Columns.ATelegram, value); }
		}
		  
		[XmlAttribute("AInstagram")]
		[Bindable(true)]
        [DataMember]
		public string AInstagram 
		{
			get { return GetColumnValue<string>(Columns.AInstagram); }
			set { SetColumnValue(Columns.AInstagram, value); }
		}
		  
		[XmlAttribute("AAparat")]
		[Bindable(true)]
        [DataMember]
		public string AAparat 
		{
			get { return GetColumnValue<string>(Columns.AAparat); }
			set { SetColumnValue(Columns.AAparat, value); }
		}
		  
		[XmlAttribute("AImg1")]
		[Bindable(true)]
        [DataMember]
		public string AImg1 
		{
			get { return GetColumnValue<string>(Columns.AImg1); }
			set { SetColumnValue(Columns.AImg1, value); }
		}
		  
		[XmlAttribute("AImg2")]
		[Bindable(true)]
        [DataMember]
		public string AImg2 
		{
			get { return GetColumnValue<string>(Columns.AImg2); }
			set { SetColumnValue(Columns.AImg2, value); }
		}
		  
		[XmlAttribute("AWhatsapp")]
		[Bindable(true)]
        [DataMember]
		public string AWhatsapp 
		{
			get { return GetColumnValue<string>(Columns.AWhatsapp); }
			set { SetColumnValue(Columns.AWhatsapp, value); }
		}
		  
		[XmlAttribute("LastDoctorType")]
		[Bindable(true)]
        [DataMember]
		public byte? LastDoctorType 
		{
			get { return GetColumnValue<byte?>(Columns.LastDoctorType); }
			set { SetColumnValue(Columns.LastDoctorType, value); }
		}
		  
		[XmlAttribute("AFooterText")]
		[Bindable(true)]
        [DataMember]
		public string AFooterText 
		{
			get { return GetColumnValue<string>(Columns.AFooterText); }
			set { SetColumnValue(Columns.AFooterText, value); }
		}
		  
		[XmlAttribute("AAddress")]
		[Bindable(true)]
        [DataMember]
		public string AAddress 
		{
			get { return GetColumnValue<string>(Columns.AAddress); }
			set { SetColumnValue(Columns.AAddress, value); }
		}
		  
		[XmlAttribute("AArDescription")]
		[Bindable(true)]
        [DataMember]
		public string AArDescription 
		{
			get { return GetColumnValue<string>(Columns.AArDescription); }
			set { SetColumnValue(Columns.AArDescription, value); }
		}
		  
		[XmlAttribute("AEnDescription")]
		[Bindable(true)]
        [DataMember]
		public string AEnDescription 
		{
			get { return GetColumnValue<string>(Columns.AEnDescription); }
			set { SetColumnValue(Columns.AEnDescription, value); }
		}
		  
		[XmlAttribute("AArAddress")]
		[Bindable(true)]
        [DataMember]
		public string AArAddress 
		{
			get { return GetColumnValue<string>(Columns.AArAddress); }
			set { SetColumnValue(Columns.AArAddress, value); }
		}
		  
		[XmlAttribute("AEnAddress")]
		[Bindable(true)]
        [DataMember]
		public string AEnAddress 
		{
			get { return GetColumnValue<string>(Columns.AEnAddress); }
			set { SetColumnValue(Columns.AEnAddress, value); }
		}
		  
		[XmlAttribute("AArFooterText")]
		[Bindable(true)]
        [DataMember]
		public string AArFooterText 
		{
			get { return GetColumnValue<string>(Columns.AArFooterText); }
			set { SetColumnValue(Columns.AArFooterText, value); }
		}
		  
		[XmlAttribute("AEnFooterText")]
		[Bindable(true)]
        [DataMember]
		public string AEnFooterText 
		{
			get { return GetColumnValue<string>(Columns.AEnFooterText); }
			set { SetColumnValue(Columns.AEnFooterText, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varADescription,string varATel,string varAMobile,string varAEmail,string varATelegram,string varAInstagram,string varAAparat,string varAImg1,string varAImg2,string varAWhatsapp,byte? varLastDoctorType,string varAFooterText,string varAAddress,string varAArDescription,string varAEnDescription,string varAArAddress,string varAEnAddress,string varAArFooterText,string varAEnFooterText)
		{
			TblAbout item = new TblAbout();
			
			item.ADescription = varADescription;
			
			item.ATel = varATel;
			
			item.AMobile = varAMobile;
			
			item.AEmail = varAEmail;
			
			item.ATelegram = varATelegram;
			
			item.AInstagram = varAInstagram;
			
			item.AAparat = varAAparat;
			
			item.AImg1 = varAImg1;
			
			item.AImg2 = varAImg2;
			
			item.AWhatsapp = varAWhatsapp;
			
			item.LastDoctorType = varLastDoctorType;
			
			item.AFooterText = varAFooterText;
			
			item.AAddress = varAAddress;
			
			item.AArDescription = varAArDescription;
			
			item.AEnDescription = varAEnDescription;
			
			item.AArAddress = varAArAddress;
			
			item.AEnAddress = varAEnAddress;
			
			item.AArFooterText = varAArFooterText;
			
			item.AEnFooterText = varAEnFooterText;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varADescription,string varATel,string varAMobile,string varAEmail,string varATelegram,string varAInstagram,string varAAparat,string varAImg1,string varAImg2,string varAWhatsapp,byte? varLastDoctorType,string varAFooterText,string varAAddress,string varAArDescription,string varAEnDescription,string varAArAddress,string varAEnAddress,string varAArFooterText,string varAEnFooterText)
		{
			TblAbout item = new TblAbout();
			
				item.Id = varId;
			
				item.ADescription = varADescription;
			
				item.ATel = varATel;
			
				item.AMobile = varAMobile;
			
				item.AEmail = varAEmail;
			
				item.ATelegram = varATelegram;
			
				item.AInstagram = varAInstagram;
			
				item.AAparat = varAAparat;
			
				item.AImg1 = varAImg1;
			
				item.AImg2 = varAImg2;
			
				item.AWhatsapp = varAWhatsapp;
			
				item.LastDoctorType = varLastDoctorType;
			
				item.AFooterText = varAFooterText;
			
				item.AAddress = varAAddress;
			
				item.AArDescription = varAArDescription;
			
				item.AEnDescription = varAEnDescription;
			
				item.AArAddress = varAArAddress;
			
				item.AEnAddress = varAEnAddress;
			
				item.AArFooterText = varAArFooterText;
			
				item.AEnFooterText = varAEnFooterText;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ADescriptionColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ATelColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn AMobileColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn AEmailColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn ATelegramColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn AInstagramColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn AAparatColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn AImg1Column
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn AImg2Column
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn AWhatsappColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn LastDoctorTypeColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn AFooterTextColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn AAddressColumn
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        public static TableSchema.TableColumn AArDescriptionColumn
        {
            get { return Schema.Columns[14]; }
        }
        
        
        
        public static TableSchema.TableColumn AEnDescriptionColumn
        {
            get { return Schema.Columns[15]; }
        }
        
        
        
        public static TableSchema.TableColumn AArAddressColumn
        {
            get { return Schema.Columns[16]; }
        }
        
        
        
        public static TableSchema.TableColumn AEnAddressColumn
        {
            get { return Schema.Columns[17]; }
        }
        
        
        
        public static TableSchema.TableColumn AArFooterTextColumn
        {
            get { return Schema.Columns[18]; }
        }
        
        
        
        public static TableSchema.TableColumn AEnFooterTextColumn
        {
            get { return Schema.Columns[19]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string ADescription = @"aDescription";
			 public static string ATel = @"aTel";
			 public static string AMobile = @"aMobile";
			 public static string AEmail = @"aEmail";
			 public static string ATelegram = @"aTelegram";
			 public static string AInstagram = @"aInstagram";
			 public static string AAparat = @"aAparat";
			 public static string AImg1 = @"aImg1";
			 public static string AImg2 = @"aImg2";
			 public static string AWhatsapp = @"aWhatsapp";
			 public static string LastDoctorType = @"lastDoctorType";
			 public static string AFooterText = @"aFooterText";
			 public static string AAddress = @"aAddress";
			 public static string AArDescription = @"aArDescription";
			 public static string AEnDescription = @"aEnDescription";
			 public static string AArAddress = @"aArAddress";
			 public static string AEnAddress = @"aEnAddress";
			 public static string AArFooterText = @"aArFooterText";
			 public static string AEnFooterText = @"aEnFooterText";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
