using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblAppointmentLog
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblAppointmentLogController
    {
        // Preload our schema..
        TblAppointmentLog thisSchemaLoad = new TblAppointmentLog();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblAppointmentLogCollection FetchAll()
        {
            TblAppointmentLogCollection coll = new TblAppointmentLogCollection();
            Query qry = new Query(TblAppointmentLog.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAppointmentLogCollection FetchByID(object Id)
        {
            TblAppointmentLogCollection coll = new TblAppointmentLogCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAppointmentLogCollection FetchByQuery(Query qry)
        {
            TblAppointmentLogCollection coll = new TblAppointmentLogCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblAppointmentLog.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblAppointmentLog.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(DateTime? SaveDate,string Inputs,string Description,int? DoctorId,DateTime? AppointmentDate,string ErrMsg)
	    {
		    TblAppointmentLog item = new TblAppointmentLog();
		    
            item.SaveDate = SaveDate;
            
            item.Inputs = Inputs;
            
            item.Description = Description;
            
            item.DoctorId = DoctorId;
            
            item.AppointmentDate = AppointmentDate;
            
            item.ErrMsg = ErrMsg;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,DateTime? SaveDate,string Inputs,string Description,int? DoctorId,DateTime? AppointmentDate,string ErrMsg)
	    {
		    TblAppointmentLog item = new TblAppointmentLog();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.SaveDate = SaveDate;
				
			item.Inputs = Inputs;
				
			item.Description = Description;
				
			item.DoctorId = DoctorId;
				
			item.AppointmentDate = AppointmentDate;
				
			item.ErrMsg = ErrMsg;
				
	        item.Save(UserName);
	    }
    }
}
