using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblAbout
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblAboutController
    {
        // Preload our schema..
        TblAbout thisSchemaLoad = new TblAbout();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblAboutCollection FetchAll()
        {
            TblAboutCollection coll = new TblAboutCollection();
            Query qry = new Query(TblAbout.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAboutCollection FetchByID(object Id)
        {
            TblAboutCollection coll = new TblAboutCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAboutCollection FetchByQuery(Query qry)
        {
            TblAboutCollection coll = new TblAboutCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblAbout.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblAbout.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string ADescription,string ATel,string AMobile,string AEmail,string ATelegram,string AInstagram,string AAparat,string AImg1,string AImg2,string AWhatsapp,byte? LastDoctorType,string AFooterText,string AAddress,string AArDescription,string AEnDescription,string AArAddress,string AEnAddress,string AArFooterText,string AEnFooterText)
	    {
		    TblAbout item = new TblAbout();
		    
            item.ADescription = ADescription;
            
            item.ATel = ATel;
            
            item.AMobile = AMobile;
            
            item.AEmail = AEmail;
            
            item.ATelegram = ATelegram;
            
            item.AInstagram = AInstagram;
            
            item.AAparat = AAparat;
            
            item.AImg1 = AImg1;
            
            item.AImg2 = AImg2;
            
            item.AWhatsapp = AWhatsapp;
            
            item.LastDoctorType = LastDoctorType;
            
            item.AFooterText = AFooterText;
            
            item.AAddress = AAddress;
            
            item.AArDescription = AArDescription;
            
            item.AEnDescription = AEnDescription;
            
            item.AArAddress = AArAddress;
            
            item.AEnAddress = AEnAddress;
            
            item.AArFooterText = AArFooterText;
            
            item.AEnFooterText = AEnFooterText;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string ADescription,string ATel,string AMobile,string AEmail,string ATelegram,string AInstagram,string AAparat,string AImg1,string AImg2,string AWhatsapp,byte? LastDoctorType,string AFooterText,string AAddress,string AArDescription,string AEnDescription,string AArAddress,string AEnAddress,string AArFooterText,string AEnFooterText)
	    {
		    TblAbout item = new TblAbout();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.ADescription = ADescription;
				
			item.ATel = ATel;
				
			item.AMobile = AMobile;
				
			item.AEmail = AEmail;
				
			item.ATelegram = ATelegram;
				
			item.AInstagram = AInstagram;
				
			item.AAparat = AAparat;
				
			item.AImg1 = AImg1;
				
			item.AImg2 = AImg2;
				
			item.AWhatsapp = AWhatsapp;
				
			item.LastDoctorType = LastDoctorType;
				
			item.AFooterText = AFooterText;
				
			item.AAddress = AAddress;
				
			item.AArDescription = AArDescription;
				
			item.AEnDescription = AEnDescription;
				
			item.AArAddress = AArAddress;
				
			item.AEnAddress = AEnAddress;
				
			item.AArFooterText = AArFooterText;
				
			item.AEnFooterText = AEnFooterText;
				
	        item.Save(UserName);
	    }
    }
}
