using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblAppointment
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblAppointmentController
    {
        // Preload our schema..
        TblAppointment thisSchemaLoad = new TblAppointment();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblAppointmentCollection FetchAll()
        {
            TblAppointmentCollection coll = new TblAppointmentCollection();
            Query qry = new Query(TblAppointment.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAppointmentCollection FetchByID(object Id)
        {
            TblAppointmentCollection coll = new TblAppointmentCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAppointmentCollection FetchByQuery(Query qry)
        {
            TblAppointmentCollection coll = new TblAppointmentCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblAppointment.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblAppointment.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? AShift,string ADate,string AStartTime,int? ATime,string ATrackingCode,int? AStatus,int? ADoctorId,DateTime? ADateTime,string AGroupCode)
	    {
		    TblAppointment item = new TblAppointment();
		    
            item.AShift = AShift;
            
            item.ADate = ADate;
            
            item.AStartTime = AStartTime;
            
            item.ATime = ATime;
            
            item.ATrackingCode = ATrackingCode;
            
            item.AStatus = AStatus;
            
            item.ADoctorId = ADoctorId;
            
            item.ADateTime = ADateTime;
            
            item.AGroupCode = AGroupCode;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? AShift,string ADate,string AStartTime,int? ATime,string ATrackingCode,int? AStatus,int? ADoctorId,DateTime? ADateTime,string AGroupCode)
	    {
		    TblAppointment item = new TblAppointment();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.AShift = AShift;
				
			item.ADate = ADate;
				
			item.AStartTime = AStartTime;
				
			item.ATime = ATime;
				
			item.ATrackingCode = ATrackingCode;
				
			item.AStatus = AStatus;
				
			item.ADoctorId = ADoctorId;
				
			item.ADateTime = ADateTime;
				
			item.AGroupCode = AGroupCode;
				
	        item.Save(UserName);
	    }
    }
}
