using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblAppointmentLog class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblAppointmentLogCollection : ActiveList<TblAppointmentLog, TblAppointmentLogCollection>
	{	   
		public TblAppointmentLogCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblAppointmentLogCollection</returns>
		public TblAppointmentLogCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblAppointmentLog o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblAppointmentLog table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblAppointmentLog : ActiveRecord<TblAppointmentLog>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblAppointmentLog()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblAppointmentLog(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblAppointmentLog(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblAppointmentLog(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblAppointmentLog", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"doctorya_user";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarSaveDate = new TableSchema.TableColumn(schema);
				colvarSaveDate.ColumnName = "saveDate";
				colvarSaveDate.DataType = DbType.DateTime;
				colvarSaveDate.MaxLength = 0;
				colvarSaveDate.AutoIncrement = false;
				colvarSaveDate.IsNullable = true;
				colvarSaveDate.IsPrimaryKey = false;
				colvarSaveDate.IsForeignKey = false;
				colvarSaveDate.IsReadOnly = false;
				colvarSaveDate.DefaultSetting = @"";
				colvarSaveDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSaveDate);
				
				TableSchema.TableColumn colvarInputs = new TableSchema.TableColumn(schema);
				colvarInputs.ColumnName = "inputs";
				colvarInputs.DataType = DbType.String;
				colvarInputs.MaxLength = -1;
				colvarInputs.AutoIncrement = false;
				colvarInputs.IsNullable = true;
				colvarInputs.IsPrimaryKey = false;
				colvarInputs.IsForeignKey = false;
				colvarInputs.IsReadOnly = false;
				colvarInputs.DefaultSetting = @"";
				colvarInputs.ForeignKeyTableName = "";
				schema.Columns.Add(colvarInputs);
				
				TableSchema.TableColumn colvarDescription = new TableSchema.TableColumn(schema);
				colvarDescription.ColumnName = "description";
				colvarDescription.DataType = DbType.String;
				colvarDescription.MaxLength = -1;
				colvarDescription.AutoIncrement = false;
				colvarDescription.IsNullable = true;
				colvarDescription.IsPrimaryKey = false;
				colvarDescription.IsForeignKey = false;
				colvarDescription.IsReadOnly = false;
				colvarDescription.DefaultSetting = @"";
				colvarDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDescription);
				
				TableSchema.TableColumn colvarDoctorId = new TableSchema.TableColumn(schema);
				colvarDoctorId.ColumnName = "doctorId";
				colvarDoctorId.DataType = DbType.Int32;
				colvarDoctorId.MaxLength = 0;
				colvarDoctorId.AutoIncrement = false;
				colvarDoctorId.IsNullable = true;
				colvarDoctorId.IsPrimaryKey = false;
				colvarDoctorId.IsForeignKey = false;
				colvarDoctorId.IsReadOnly = false;
				colvarDoctorId.DefaultSetting = @"";
				colvarDoctorId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDoctorId);
				
				TableSchema.TableColumn colvarAppointmentDate = new TableSchema.TableColumn(schema);
				colvarAppointmentDate.ColumnName = "appointmentDate";
				colvarAppointmentDate.DataType = DbType.DateTime;
				colvarAppointmentDate.MaxLength = 0;
				colvarAppointmentDate.AutoIncrement = false;
				colvarAppointmentDate.IsNullable = true;
				colvarAppointmentDate.IsPrimaryKey = false;
				colvarAppointmentDate.IsForeignKey = false;
				colvarAppointmentDate.IsReadOnly = false;
				colvarAppointmentDate.DefaultSetting = @"";
				colvarAppointmentDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAppointmentDate);
				
				TableSchema.TableColumn colvarErrMsg = new TableSchema.TableColumn(schema);
				colvarErrMsg.ColumnName = "errMsg";
				colvarErrMsg.DataType = DbType.String;
				colvarErrMsg.MaxLength = 500;
				colvarErrMsg.AutoIncrement = false;
				colvarErrMsg.IsNullable = true;
				colvarErrMsg.IsPrimaryKey = false;
				colvarErrMsg.IsForeignKey = false;
				colvarErrMsg.IsReadOnly = false;
				colvarErrMsg.DefaultSetting = @"";
				colvarErrMsg.ForeignKeyTableName = "";
				schema.Columns.Add(colvarErrMsg);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblAppointmentLog",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("SaveDate")]
		[Bindable(true)]
        [DataMember]
		public DateTime? SaveDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.SaveDate); }
			set { SetColumnValue(Columns.SaveDate, value); }
		}
		  
		[XmlAttribute("Inputs")]
		[Bindable(true)]
        [DataMember]
		public string Inputs 
		{
			get { return GetColumnValue<string>(Columns.Inputs); }
			set { SetColumnValue(Columns.Inputs, value); }
		}
		  
		[XmlAttribute("Description")]
		[Bindable(true)]
        [DataMember]
		public string Description 
		{
			get { return GetColumnValue<string>(Columns.Description); }
			set { SetColumnValue(Columns.Description, value); }
		}
		  
		[XmlAttribute("DoctorId")]
		[Bindable(true)]
        [DataMember]
		public int? DoctorId 
		{
			get { return GetColumnValue<int?>(Columns.DoctorId); }
			set { SetColumnValue(Columns.DoctorId, value); }
		}
		  
		[XmlAttribute("AppointmentDate")]
		[Bindable(true)]
        [DataMember]
		public DateTime? AppointmentDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.AppointmentDate); }
			set { SetColumnValue(Columns.AppointmentDate, value); }
		}
		  
		[XmlAttribute("ErrMsg")]
		[Bindable(true)]
        [DataMember]
		public string ErrMsg 
		{
			get { return GetColumnValue<string>(Columns.ErrMsg); }
			set { SetColumnValue(Columns.ErrMsg, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(DateTime? varSaveDate,string varInputs,string varDescription,int? varDoctorId,DateTime? varAppointmentDate,string varErrMsg)
		{
			TblAppointmentLog item = new TblAppointmentLog();
			
			item.SaveDate = varSaveDate;
			
			item.Inputs = varInputs;
			
			item.Description = varDescription;
			
			item.DoctorId = varDoctorId;
			
			item.AppointmentDate = varAppointmentDate;
			
			item.ErrMsg = varErrMsg;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,DateTime? varSaveDate,string varInputs,string varDescription,int? varDoctorId,DateTime? varAppointmentDate,string varErrMsg)
		{
			TblAppointmentLog item = new TblAppointmentLog();
			
				item.Id = varId;
			
				item.SaveDate = varSaveDate;
			
				item.Inputs = varInputs;
			
				item.Description = varDescription;
			
				item.DoctorId = varDoctorId;
			
				item.AppointmentDate = varAppointmentDate;
			
				item.ErrMsg = varErrMsg;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn SaveDateColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn InputsColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn DescriptionColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn DoctorIdColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn AppointmentDateColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn ErrMsgColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string SaveDate = @"saveDate";
			 public static string Inputs = @"inputs";
			 public static string Description = @"description";
			 public static string DoctorId = @"doctorId";
			 public static string AppointmentDate = @"appointmentDate";
			 public static string ErrMsg = @"errMsg";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
