using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblBlog class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblBlogCollection : ActiveList<TblBlog, TblBlogCollection>
	{	   
		public TblBlogCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblBlogCollection</returns>
		public TblBlogCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblBlog o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblBlog table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblBlog : ActiveRecord<TblBlog>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblBlog()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblBlog(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblBlog(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblBlog(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblBlog", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarBSubject = new TableSchema.TableColumn(schema);
				colvarBSubject.ColumnName = "bSubject";
				colvarBSubject.DataType = DbType.String;
				colvarBSubject.MaxLength = 200;
				colvarBSubject.AutoIncrement = false;
				colvarBSubject.IsNullable = true;
				colvarBSubject.IsPrimaryKey = false;
				colvarBSubject.IsForeignKey = false;
				colvarBSubject.IsReadOnly = false;
				colvarBSubject.DefaultSetting = @"";
				colvarBSubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBSubject);
				
				TableSchema.TableColumn colvarBSummery = new TableSchema.TableColumn(schema);
				colvarBSummery.ColumnName = "bSummery";
				colvarBSummery.DataType = DbType.String;
				colvarBSummery.MaxLength = 500;
				colvarBSummery.AutoIncrement = false;
				colvarBSummery.IsNullable = true;
				colvarBSummery.IsPrimaryKey = false;
				colvarBSummery.IsForeignKey = false;
				colvarBSummery.IsReadOnly = false;
				colvarBSummery.DefaultSetting = @"";
				colvarBSummery.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBSummery);
				
				TableSchema.TableColumn colvarBDes = new TableSchema.TableColumn(schema);
				colvarBDes.ColumnName = "bDes";
				colvarBDes.DataType = DbType.String;
				colvarBDes.MaxLength = 1073741823;
				colvarBDes.AutoIncrement = false;
				colvarBDes.IsNullable = true;
				colvarBDes.IsPrimaryKey = false;
				colvarBDes.IsForeignKey = false;
				colvarBDes.IsReadOnly = false;
				colvarBDes.DefaultSetting = @"";
				colvarBDes.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBDes);
				
				TableSchema.TableColumn colvarBKeyword = new TableSchema.TableColumn(schema);
				colvarBKeyword.ColumnName = "bKeyword";
				colvarBKeyword.DataType = DbType.String;
				colvarBKeyword.MaxLength = 200;
				colvarBKeyword.AutoIncrement = false;
				colvarBKeyword.IsNullable = true;
				colvarBKeyword.IsPrimaryKey = false;
				colvarBKeyword.IsForeignKey = false;
				colvarBKeyword.IsReadOnly = false;
				colvarBKeyword.DefaultSetting = @"";
				colvarBKeyword.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBKeyword);
				
				TableSchema.TableColumn colvarBDate = new TableSchema.TableColumn(schema);
				colvarBDate.ColumnName = "bDate";
				colvarBDate.DataType = DbType.String;
				colvarBDate.MaxLength = 20;
				colvarBDate.AutoIncrement = false;
				colvarBDate.IsNullable = true;
				colvarBDate.IsPrimaryKey = false;
				colvarBDate.IsForeignKey = false;
				colvarBDate.IsReadOnly = false;
				colvarBDate.DefaultSetting = @"";
				colvarBDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBDate);
				
				TableSchema.TableColumn colvarBPic = new TableSchema.TableColumn(schema);
				colvarBPic.ColumnName = "bPic";
				colvarBPic.DataType = DbType.String;
				colvarBPic.MaxLength = 250;
				colvarBPic.AutoIncrement = false;
				colvarBPic.IsNullable = true;
				colvarBPic.IsPrimaryKey = false;
				colvarBPic.IsForeignKey = false;
				colvarBPic.IsReadOnly = false;
				colvarBPic.DefaultSetting = @"";
				colvarBPic.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBPic);
				
				TableSchema.TableColumn colvarBWriter = new TableSchema.TableColumn(schema);
				colvarBWriter.ColumnName = "bWriter";
				colvarBWriter.DataType = DbType.String;
				colvarBWriter.MaxLength = 50;
				colvarBWriter.AutoIncrement = false;
				colvarBWriter.IsNullable = true;
				colvarBWriter.IsPrimaryKey = false;
				colvarBWriter.IsForeignKey = false;
				colvarBWriter.IsReadOnly = false;
				colvarBWriter.DefaultSetting = @"";
				colvarBWriter.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBWriter);
				
				TableSchema.TableColumn colvarBGroupFk = new TableSchema.TableColumn(schema);
				colvarBGroupFk.ColumnName = "bGroupFk";
				colvarBGroupFk.DataType = DbType.Int32;
				colvarBGroupFk.MaxLength = 0;
				colvarBGroupFk.AutoIncrement = false;
				colvarBGroupFk.IsNullable = true;
				colvarBGroupFk.IsPrimaryKey = false;
				colvarBGroupFk.IsForeignKey = false;
				colvarBGroupFk.IsReadOnly = false;
				colvarBGroupFk.DefaultSetting = @"";
				colvarBGroupFk.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBGroupFk);
				
				TableSchema.TableColumn colvarBMetaDes = new TableSchema.TableColumn(schema);
				colvarBMetaDes.ColumnName = "bMetaDes";
				colvarBMetaDes.DataType = DbType.String;
				colvarBMetaDes.MaxLength = 200;
				colvarBMetaDes.AutoIncrement = false;
				colvarBMetaDes.IsNullable = true;
				colvarBMetaDes.IsPrimaryKey = false;
				colvarBMetaDes.IsForeignKey = false;
				colvarBMetaDes.IsReadOnly = false;
				colvarBMetaDes.DefaultSetting = @"";
				colvarBMetaDes.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBMetaDes);
				
				TableSchema.TableColumn colvarBTags = new TableSchema.TableColumn(schema);
				colvarBTags.ColumnName = "bTags";
				colvarBTags.DataType = DbType.String;
				colvarBTags.MaxLength = 200;
				colvarBTags.AutoIncrement = false;
				colvarBTags.IsNullable = true;
				colvarBTags.IsPrimaryKey = false;
				colvarBTags.IsForeignKey = false;
				colvarBTags.IsReadOnly = false;
				colvarBTags.DefaultSetting = @"";
				colvarBTags.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBTags);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblBlog",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("BSubject")]
		[Bindable(true)]
        [DataMember]
		public string BSubject 
		{
			get { return GetColumnValue<string>(Columns.BSubject); }
			set { SetColumnValue(Columns.BSubject, value); }
		}
		  
		[XmlAttribute("BSummery")]
		[Bindable(true)]
        [DataMember]
		public string BSummery 
		{
			get { return GetColumnValue<string>(Columns.BSummery); }
			set { SetColumnValue(Columns.BSummery, value); }
		}
		  
		[XmlAttribute("BDes")]
		[Bindable(true)]
        [DataMember]
		public string BDes 
		{
			get { return GetColumnValue<string>(Columns.BDes); }
			set { SetColumnValue(Columns.BDes, value); }
		}
		  
		[XmlAttribute("BKeyword")]
		[Bindable(true)]
        [DataMember]
		public string BKeyword 
		{
			get { return GetColumnValue<string>(Columns.BKeyword); }
			set { SetColumnValue(Columns.BKeyword, value); }
		}
		  
		[XmlAttribute("BDate")]
		[Bindable(true)]
        [DataMember]
		public string BDate 
		{
			get { return GetColumnValue<string>(Columns.BDate); }
			set { SetColumnValue(Columns.BDate, value); }
		}
		  
		[XmlAttribute("BPic")]
		[Bindable(true)]
        [DataMember]
		public string BPic 
		{
			get { return GetColumnValue<string>(Columns.BPic); }
			set { SetColumnValue(Columns.BPic, value); }
		}
		  
		[XmlAttribute("BWriter")]
		[Bindable(true)]
        [DataMember]
		public string BWriter 
		{
			get { return GetColumnValue<string>(Columns.BWriter); }
			set { SetColumnValue(Columns.BWriter, value); }
		}
		  
		[XmlAttribute("BGroupFk")]
		[Bindable(true)]
        [DataMember]
		public int? BGroupFk 
		{
			get { return GetColumnValue<int?>(Columns.BGroupFk); }
			set { SetColumnValue(Columns.BGroupFk, value); }
		}
		  
		[XmlAttribute("BMetaDes")]
		[Bindable(true)]
        [DataMember]
		public string BMetaDes 
		{
			get { return GetColumnValue<string>(Columns.BMetaDes); }
			set { SetColumnValue(Columns.BMetaDes, value); }
		}
		  
		[XmlAttribute("BTags")]
		[Bindable(true)]
        [DataMember]
		public string BTags 
		{
			get { return GetColumnValue<string>(Columns.BTags); }
			set { SetColumnValue(Columns.BTags, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varBSubject,string varBSummery,string varBDes,string varBKeyword,string varBDate,string varBPic,string varBWriter,int? varBGroupFk,string varBMetaDes,string varBTags)
		{
			TblBlog item = new TblBlog();
			
			item.BSubject = varBSubject;
			
			item.BSummery = varBSummery;
			
			item.BDes = varBDes;
			
			item.BKeyword = varBKeyword;
			
			item.BDate = varBDate;
			
			item.BPic = varBPic;
			
			item.BWriter = varBWriter;
			
			item.BGroupFk = varBGroupFk;
			
			item.BMetaDes = varBMetaDes;
			
			item.BTags = varBTags;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varBSubject,string varBSummery,string varBDes,string varBKeyword,string varBDate,string varBPic,string varBWriter,int? varBGroupFk,string varBMetaDes,string varBTags)
		{
			TblBlog item = new TblBlog();
			
				item.Id = varId;
			
				item.BSubject = varBSubject;
			
				item.BSummery = varBSummery;
			
				item.BDes = varBDes;
			
				item.BKeyword = varBKeyword;
			
				item.BDate = varBDate;
			
				item.BPic = varBPic;
			
				item.BWriter = varBWriter;
			
				item.BGroupFk = varBGroupFk;
			
				item.BMetaDes = varBMetaDes;
			
				item.BTags = varBTags;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn BSubjectColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn BSummeryColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn BDesColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn BKeywordColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn BDateColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn BPicColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn BWriterColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn BGroupFkColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn BMetaDesColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn BTagsColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string BSubject = @"bSubject";
			 public static string BSummery = @"bSummery";
			 public static string BDes = @"bDes";
			 public static string BKeyword = @"bKeyword";
			 public static string BDate = @"bDate";
			 public static string BPic = @"bPic";
			 public static string BWriter = @"bWriter";
			 public static string BGroupFk = @"bGroupFk";
			 public static string BMetaDes = @"bMetaDes";
			 public static string BTags = @"bTags";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
