using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblBanner class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblBannerCollection : ActiveList<TblBanner, TblBannerCollection>
	{	   
		public TblBannerCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblBannerCollection</returns>
		public TblBannerCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblBanner o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblBanner table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblBanner : ActiveRecord<TblBanner>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblBanner()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblBanner(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblBanner(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblBanner(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblBanner", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarBSubject = new TableSchema.TableColumn(schema);
				colvarBSubject.ColumnName = "bSubject";
				colvarBSubject.DataType = DbType.String;
				colvarBSubject.MaxLength = 50;
				colvarBSubject.AutoIncrement = false;
				colvarBSubject.IsNullable = true;
				colvarBSubject.IsPrimaryKey = false;
				colvarBSubject.IsForeignKey = false;
				colvarBSubject.IsReadOnly = false;
				colvarBSubject.DefaultSetting = @"";
				colvarBSubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBSubject);
				
				TableSchema.TableColumn colvarBSubTitle = new TableSchema.TableColumn(schema);
				colvarBSubTitle.ColumnName = "bSubTitle";
				colvarBSubTitle.DataType = DbType.String;
				colvarBSubTitle.MaxLength = 80;
				colvarBSubTitle.AutoIncrement = false;
				colvarBSubTitle.IsNullable = true;
				colvarBSubTitle.IsPrimaryKey = false;
				colvarBSubTitle.IsForeignKey = false;
				colvarBSubTitle.IsReadOnly = false;
				colvarBSubTitle.DefaultSetting = @"";
				colvarBSubTitle.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBSubTitle);
				
				TableSchema.TableColumn colvarBText1 = new TableSchema.TableColumn(schema);
				colvarBText1.ColumnName = "bText1";
				colvarBText1.DataType = DbType.String;
				colvarBText1.MaxLength = 50;
				colvarBText1.AutoIncrement = false;
				colvarBText1.IsNullable = true;
				colvarBText1.IsPrimaryKey = false;
				colvarBText1.IsForeignKey = false;
				colvarBText1.IsReadOnly = false;
				colvarBText1.DefaultSetting = @"";
				colvarBText1.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBText1);
				
				TableSchema.TableColumn colvarBPriority = new TableSchema.TableColumn(schema);
				colvarBPriority.ColumnName = "bPriority";
				colvarBPriority.DataType = DbType.Int32;
				colvarBPriority.MaxLength = 0;
				colvarBPriority.AutoIncrement = false;
				colvarBPriority.IsNullable = true;
				colvarBPriority.IsPrimaryKey = false;
				colvarBPriority.IsForeignKey = false;
				colvarBPriority.IsReadOnly = false;
				colvarBPriority.DefaultSetting = @"";
				colvarBPriority.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBPriority);
				
				TableSchema.TableColumn colvarBImage = new TableSchema.TableColumn(schema);
				colvarBImage.ColumnName = "bImage";
				colvarBImage.DataType = DbType.String;
				colvarBImage.MaxLength = 250;
				colvarBImage.AutoIncrement = false;
				colvarBImage.IsNullable = true;
				colvarBImage.IsPrimaryKey = false;
				colvarBImage.IsForeignKey = false;
				colvarBImage.IsReadOnly = false;
				colvarBImage.DefaultSetting = @"";
				colvarBImage.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBImage);
				
				TableSchema.TableColumn colvarBLink = new TableSchema.TableColumn(schema);
				colvarBLink.ColumnName = "bLink";
				colvarBLink.DataType = DbType.String;
				colvarBLink.MaxLength = 500;
				colvarBLink.AutoIncrement = false;
				colvarBLink.IsNullable = true;
				colvarBLink.IsPrimaryKey = false;
				colvarBLink.IsForeignKey = false;
				colvarBLink.IsReadOnly = false;
				colvarBLink.DefaultSetting = @"";
				colvarBLink.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBLink);
				
				TableSchema.TableColumn colvarBStatus = new TableSchema.TableColumn(schema);
				colvarBStatus.ColumnName = "bStatus";
				colvarBStatus.DataType = DbType.Boolean;
				colvarBStatus.MaxLength = 0;
				colvarBStatus.AutoIncrement = false;
				colvarBStatus.IsNullable = true;
				colvarBStatus.IsPrimaryKey = false;
				colvarBStatus.IsForeignKey = false;
				colvarBStatus.IsReadOnly = false;
				colvarBStatus.DefaultSetting = @"";
				colvarBStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBStatus);
				
				TableSchema.TableColumn colvarBStateFk = new TableSchema.TableColumn(schema);
				colvarBStateFk.ColumnName = "bStateFk";
				colvarBStateFk.DataType = DbType.Int32;
				colvarBStateFk.MaxLength = 0;
				colvarBStateFk.AutoIncrement = false;
				colvarBStateFk.IsNullable = true;
				colvarBStateFk.IsPrimaryKey = false;
				colvarBStateFk.IsForeignKey = false;
				colvarBStateFk.IsReadOnly = false;
				colvarBStateFk.DefaultSetting = @"";
				colvarBStateFk.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBStateFk);
				
				TableSchema.TableColumn colvarBLanguage = new TableSchema.TableColumn(schema);
				colvarBLanguage.ColumnName = "bLanguage";
				colvarBLanguage.DataType = DbType.Byte;
				colvarBLanguage.MaxLength = 0;
				colvarBLanguage.AutoIncrement = false;
				colvarBLanguage.IsNullable = true;
				colvarBLanguage.IsPrimaryKey = false;
				colvarBLanguage.IsForeignKey = false;
				colvarBLanguage.IsReadOnly = false;
				colvarBLanguage.DefaultSetting = @"";
				colvarBLanguage.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBLanguage);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblBanner",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("BSubject")]
		[Bindable(true)]
        [DataMember]
		public string BSubject 
		{
			get { return GetColumnValue<string>(Columns.BSubject); }
			set { SetColumnValue(Columns.BSubject, value); }
		}
		  
		[XmlAttribute("BSubTitle")]
		[Bindable(true)]
        [DataMember]
		public string BSubTitle 
		{
			get { return GetColumnValue<string>(Columns.BSubTitle); }
			set { SetColumnValue(Columns.BSubTitle, value); }
		}
		  
		[XmlAttribute("BText1")]
		[Bindable(true)]
        [DataMember]
		public string BText1 
		{
			get { return GetColumnValue<string>(Columns.BText1); }
			set { SetColumnValue(Columns.BText1, value); }
		}
		  
		[XmlAttribute("BPriority")]
		[Bindable(true)]
        [DataMember]
		public int? BPriority 
		{
			get { return GetColumnValue<int?>(Columns.BPriority); }
			set { SetColumnValue(Columns.BPriority, value); }
		}
		  
		[XmlAttribute("BImage")]
		[Bindable(true)]
        [DataMember]
		public string BImage 
		{
			get { return GetColumnValue<string>(Columns.BImage); }
			set { SetColumnValue(Columns.BImage, value); }
		}
		  
		[XmlAttribute("BLink")]
		[Bindable(true)]
        [DataMember]
		public string BLink 
		{
			get { return GetColumnValue<string>(Columns.BLink); }
			set { SetColumnValue(Columns.BLink, value); }
		}
		  
		[XmlAttribute("BStatus")]
		[Bindable(true)]
        [DataMember]
		public bool? BStatus 
		{
			get { return GetColumnValue<bool?>(Columns.BStatus); }
			set { SetColumnValue(Columns.BStatus, value); }
		}
		  
		[XmlAttribute("BStateFk")]
		[Bindable(true)]
        [DataMember]
		public int? BStateFk 
		{
			get { return GetColumnValue<int?>(Columns.BStateFk); }
			set { SetColumnValue(Columns.BStateFk, value); }
		}
		  
		[XmlAttribute("BLanguage")]
		[Bindable(true)]
        [DataMember]
		public byte? BLanguage 
		{
			get { return GetColumnValue<byte?>(Columns.BLanguage); }
			set { SetColumnValue(Columns.BLanguage, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varBSubject,string varBSubTitle,string varBText1,int? varBPriority,string varBImage,string varBLink,bool? varBStatus,int? varBStateFk,byte? varBLanguage)
		{
			TblBanner item = new TblBanner();
			
			item.BSubject = varBSubject;
			
			item.BSubTitle = varBSubTitle;
			
			item.BText1 = varBText1;
			
			item.BPriority = varBPriority;
			
			item.BImage = varBImage;
			
			item.BLink = varBLink;
			
			item.BStatus = varBStatus;
			
			item.BStateFk = varBStateFk;
			
			item.BLanguage = varBLanguage;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varBSubject,string varBSubTitle,string varBText1,int? varBPriority,string varBImage,string varBLink,bool? varBStatus,int? varBStateFk,byte? varBLanguage)
		{
			TblBanner item = new TblBanner();
			
				item.Id = varId;
			
				item.BSubject = varBSubject;
			
				item.BSubTitle = varBSubTitle;
			
				item.BText1 = varBText1;
			
				item.BPriority = varBPriority;
			
				item.BImage = varBImage;
			
				item.BLink = varBLink;
			
				item.BStatus = varBStatus;
			
				item.BStateFk = varBStateFk;
			
				item.BLanguage = varBLanguage;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn BSubjectColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn BSubTitleColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn BText1Column
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn BPriorityColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn BImageColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn BLinkColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn BStatusColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn BStateFkColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn BLanguageColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string BSubject = @"bSubject";
			 public static string BSubTitle = @"bSubTitle";
			 public static string BText1 = @"bText1";
			 public static string BPriority = @"bPriority";
			 public static string BImage = @"bImage";
			 public static string BLink = @"bLink";
			 public static string BStatus = @"bStatus";
			 public static string BStateFk = @"bStateFk";
			 public static string BLanguage = @"bLanguage";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
