using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblBranch class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblBranchCollection : ActiveList<TblBranch, TblBranchCollection>
	{	   
		public TblBranchCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblBranchCollection</returns>
		public TblBranchCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblBranch o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblBranch table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblBranch : ActiveRecord<TblBranch>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblBranch()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblBranch(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblBranch(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblBranch(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblBranch", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarBSubject = new TableSchema.TableColumn(schema);
				colvarBSubject.ColumnName = "bSubject";
				colvarBSubject.DataType = DbType.String;
				colvarBSubject.MaxLength = 50;
				colvarBSubject.AutoIncrement = false;
				colvarBSubject.IsNullable = true;
				colvarBSubject.IsPrimaryKey = false;
				colvarBSubject.IsForeignKey = false;
				colvarBSubject.IsReadOnly = false;
				colvarBSubject.DefaultSetting = @"";
				colvarBSubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBSubject);
				
				TableSchema.TableColumn colvarBIcon = new TableSchema.TableColumn(schema);
				colvarBIcon.ColumnName = "bIcon";
				colvarBIcon.DataType = DbType.String;
				colvarBIcon.MaxLength = 150;
				colvarBIcon.AutoIncrement = false;
				colvarBIcon.IsNullable = true;
				colvarBIcon.IsPrimaryKey = false;
				colvarBIcon.IsForeignKey = false;
				colvarBIcon.IsReadOnly = false;
				colvarBIcon.DefaultSetting = @"";
				colvarBIcon.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBIcon);
				
				TableSchema.TableColumn colvarBKeyword = new TableSchema.TableColumn(schema);
				colvarBKeyword.ColumnName = "bKeyword";
				colvarBKeyword.DataType = DbType.String;
				colvarBKeyword.MaxLength = 200;
				colvarBKeyword.AutoIncrement = false;
				colvarBKeyword.IsNullable = true;
				colvarBKeyword.IsPrimaryKey = false;
				colvarBKeyword.IsForeignKey = false;
				colvarBKeyword.IsReadOnly = false;
				colvarBKeyword.DefaultSetting = @"";
				colvarBKeyword.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBKeyword);
				
				TableSchema.TableColumn colvarBIsDeleted = new TableSchema.TableColumn(schema);
				colvarBIsDeleted.ColumnName = "bIsDeleted";
				colvarBIsDeleted.DataType = DbType.Boolean;
				colvarBIsDeleted.MaxLength = 0;
				colvarBIsDeleted.AutoIncrement = false;
				colvarBIsDeleted.IsNullable = true;
				colvarBIsDeleted.IsPrimaryKey = false;
				colvarBIsDeleted.IsForeignKey = false;
				colvarBIsDeleted.IsReadOnly = false;
				colvarBIsDeleted.DefaultSetting = @"";
				colvarBIsDeleted.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBIsDeleted);
				
				TableSchema.TableColumn colvarBArSubject = new TableSchema.TableColumn(schema);
				colvarBArSubject.ColumnName = "bArSubject";
				colvarBArSubject.DataType = DbType.String;
				colvarBArSubject.MaxLength = 50;
				colvarBArSubject.AutoIncrement = false;
				colvarBArSubject.IsNullable = true;
				colvarBArSubject.IsPrimaryKey = false;
				colvarBArSubject.IsForeignKey = false;
				colvarBArSubject.IsReadOnly = false;
				colvarBArSubject.DefaultSetting = @"";
				colvarBArSubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBArSubject);
				
				TableSchema.TableColumn colvarBEnSubject = new TableSchema.TableColumn(schema);
				colvarBEnSubject.ColumnName = "bEnSubject";
				colvarBEnSubject.DataType = DbType.String;
				colvarBEnSubject.MaxLength = 50;
				colvarBEnSubject.AutoIncrement = false;
				colvarBEnSubject.IsNullable = true;
				colvarBEnSubject.IsPrimaryKey = false;
				colvarBEnSubject.IsForeignKey = false;
				colvarBEnSubject.IsReadOnly = false;
				colvarBEnSubject.DefaultSetting = @"";
				colvarBEnSubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBEnSubject);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblBranch",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("BSubject")]
		[Bindable(true)]
        [DataMember]
		public string BSubject 
		{
			get { return GetColumnValue<string>(Columns.BSubject); }
			set { SetColumnValue(Columns.BSubject, value); }
		}
		  
		[XmlAttribute("BIcon")]
		[Bindable(true)]
        [DataMember]
		public string BIcon 
		{
			get { return GetColumnValue<string>(Columns.BIcon); }
			set { SetColumnValue(Columns.BIcon, value); }
		}
		  
		[XmlAttribute("BKeyword")]
		[Bindable(true)]
        [DataMember]
		public string BKeyword 
		{
			get { return GetColumnValue<string>(Columns.BKeyword); }
			set { SetColumnValue(Columns.BKeyword, value); }
		}
		  
		[XmlAttribute("BIsDeleted")]
		[Bindable(true)]
        [DataMember]
		public bool? BIsDeleted 
		{
			get { return GetColumnValue<bool?>(Columns.BIsDeleted); }
			set { SetColumnValue(Columns.BIsDeleted, value); }
		}
		  
		[XmlAttribute("BArSubject")]
		[Bindable(true)]
        [DataMember]
		public string BArSubject 
		{
			get { return GetColumnValue<string>(Columns.BArSubject); }
			set { SetColumnValue(Columns.BArSubject, value); }
		}
		  
		[XmlAttribute("BEnSubject")]
		[Bindable(true)]
        [DataMember]
		public string BEnSubject 
		{
			get { return GetColumnValue<string>(Columns.BEnSubject); }
			set { SetColumnValue(Columns.BEnSubject, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varBSubject,string varBIcon,string varBKeyword,bool? varBIsDeleted,string varBArSubject,string varBEnSubject)
		{
			TblBranch item = new TblBranch();
			
			item.BSubject = varBSubject;
			
			item.BIcon = varBIcon;
			
			item.BKeyword = varBKeyword;
			
			item.BIsDeleted = varBIsDeleted;
			
			item.BArSubject = varBArSubject;
			
			item.BEnSubject = varBEnSubject;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varBSubject,string varBIcon,string varBKeyword,bool? varBIsDeleted,string varBArSubject,string varBEnSubject)
		{
			TblBranch item = new TblBranch();
			
				item.Id = varId;
			
				item.BSubject = varBSubject;
			
				item.BIcon = varBIcon;
			
				item.BKeyword = varBKeyword;
			
				item.BIsDeleted = varBIsDeleted;
			
				item.BArSubject = varBArSubject;
			
				item.BEnSubject = varBEnSubject;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn BSubjectColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn BIconColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn BKeywordColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn BIsDeletedColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn BArSubjectColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn BEnSubjectColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string BSubject = @"bSubject";
			 public static string BIcon = @"bIcon";
			 public static string BKeyword = @"bKeyword";
			 public static string BIsDeleted = @"bIsDeleted";
			 public static string BArSubject = @"bArSubject";
			 public static string BEnSubject = @"bEnSubject";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
