using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblCity class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblCityCollection : ActiveList<TblCity, TblCityCollection>
	{	   
		public TblCityCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblCityCollection</returns>
		public TblCityCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblCity o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblCity table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblCity : ActiveRecord<TblCity>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblCity()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblCity(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblCity(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblCity(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblCity", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarCName = new TableSchema.TableColumn(schema);
				colvarCName.ColumnName = "cName";
				colvarCName.DataType = DbType.String;
				colvarCName.MaxLength = 50;
				colvarCName.AutoIncrement = false;
				colvarCName.IsNullable = true;
				colvarCName.IsPrimaryKey = false;
				colvarCName.IsForeignKey = false;
				colvarCName.IsReadOnly = false;
				colvarCName.DefaultSetting = @"";
				colvarCName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCName);
				
				TableSchema.TableColumn colvarCIsDeleted = new TableSchema.TableColumn(schema);
				colvarCIsDeleted.ColumnName = "cIsDeleted";
				colvarCIsDeleted.DataType = DbType.Boolean;
				colvarCIsDeleted.MaxLength = 0;
				colvarCIsDeleted.AutoIncrement = false;
				colvarCIsDeleted.IsNullable = true;
				colvarCIsDeleted.IsPrimaryKey = false;
				colvarCIsDeleted.IsForeignKey = false;
				colvarCIsDeleted.IsReadOnly = false;
				colvarCIsDeleted.DefaultSetting = @"";
				colvarCIsDeleted.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCIsDeleted);
				
				TableSchema.TableColumn colvarCStateFk = new TableSchema.TableColumn(schema);
				colvarCStateFk.ColumnName = "cStateFk";
				colvarCStateFk.DataType = DbType.Int32;
				colvarCStateFk.MaxLength = 0;
				colvarCStateFk.AutoIncrement = false;
				colvarCStateFk.IsNullable = true;
				colvarCStateFk.IsPrimaryKey = false;
				colvarCStateFk.IsForeignKey = false;
				colvarCStateFk.IsReadOnly = false;
				colvarCStateFk.DefaultSetting = @"";
				colvarCStateFk.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCStateFk);
				
				TableSchema.TableColumn colvarCEnName = new TableSchema.TableColumn(schema);
				colvarCEnName.ColumnName = "cEnName";
				colvarCEnName.DataType = DbType.String;
				colvarCEnName.MaxLength = 50;
				colvarCEnName.AutoIncrement = false;
				colvarCEnName.IsNullable = true;
				colvarCEnName.IsPrimaryKey = false;
				colvarCEnName.IsForeignKey = false;
				colvarCEnName.IsReadOnly = false;
				colvarCEnName.DefaultSetting = @"";
				colvarCEnName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCEnName);
				
				TableSchema.TableColumn colvarCArName = new TableSchema.TableColumn(schema);
				colvarCArName.ColumnName = "cArName";
				colvarCArName.DataType = DbType.String;
				colvarCArName.MaxLength = 50;
				colvarCArName.AutoIncrement = false;
				colvarCArName.IsNullable = true;
				colvarCArName.IsPrimaryKey = false;
				colvarCArName.IsForeignKey = false;
				colvarCArName.IsReadOnly = false;
				colvarCArName.DefaultSetting = @"";
				colvarCArName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCArName);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblCity",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("CName")]
		[Bindable(true)]
        [DataMember]
		public string CName 
		{
			get { return GetColumnValue<string>(Columns.CName); }
			set { SetColumnValue(Columns.CName, value); }
		}
		  
		[XmlAttribute("CIsDeleted")]
		[Bindable(true)]
        [DataMember]
		public bool? CIsDeleted 
		{
			get { return GetColumnValue<bool?>(Columns.CIsDeleted); }
			set { SetColumnValue(Columns.CIsDeleted, value); }
		}
		  
		[XmlAttribute("CStateFk")]
		[Bindable(true)]
        [DataMember]
		public int? CStateFk 
		{
			get { return GetColumnValue<int?>(Columns.CStateFk); }
			set { SetColumnValue(Columns.CStateFk, value); }
		}
		  
		[XmlAttribute("CEnName")]
		[Bindable(true)]
        [DataMember]
		public string CEnName 
		{
			get { return GetColumnValue<string>(Columns.CEnName); }
			set { SetColumnValue(Columns.CEnName, value); }
		}
		  
		[XmlAttribute("CArName")]
		[Bindable(true)]
        [DataMember]
		public string CArName 
		{
			get { return GetColumnValue<string>(Columns.CArName); }
			set { SetColumnValue(Columns.CArName, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varCName,bool? varCIsDeleted,int? varCStateFk,string varCEnName,string varCArName)
		{
			TblCity item = new TblCity();
			
			item.CName = varCName;
			
			item.CIsDeleted = varCIsDeleted;
			
			item.CStateFk = varCStateFk;
			
			item.CEnName = varCEnName;
			
			item.CArName = varCArName;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varCName,bool? varCIsDeleted,int? varCStateFk,string varCEnName,string varCArName)
		{
			TblCity item = new TblCity();
			
				item.Id = varId;
			
				item.CName = varCName;
			
				item.CIsDeleted = varCIsDeleted;
			
				item.CStateFk = varCStateFk;
			
				item.CEnName = varCEnName;
			
				item.CArName = varCArName;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn CNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn CIsDeletedColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn CStateFkColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn CEnNameColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn CArNameColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string CName = @"cName";
			 public static string CIsDeleted = @"cIsDeleted";
			 public static string CStateFk = @"cStateFk";
			 public static string CEnName = @"cEnName";
			 public static string CArName = @"cArName";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
