using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblCard
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblCardController
    {
        // Preload our schema..
        TblCard thisSchemaLoad = new TblCard();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblCardCollection FetchAll()
        {
            TblCardCollection coll = new TblCardCollection();
            Query qry = new Query(TblCard.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCardCollection FetchByID(object Id)
        {
            TblCardCollection coll = new TblCardCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCardCollection FetchByQuery(Query qry)
        {
            TblCardCollection coll = new TblCardCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblCard.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblCard.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string CSubject,string CLink,string CPic,bool? CStatus,int? CStateFk)
	    {
		    TblCard item = new TblCard();
		    
            item.CSubject = CSubject;
            
            item.CLink = CLink;
            
            item.CPic = CPic;
            
            item.CStatus = CStatus;
            
            item.CStateFk = CStateFk;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string CSubject,string CLink,string CPic,bool? CStatus,int? CStateFk)
	    {
		    TblCard item = new TblCard();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.CSubject = CSubject;
				
			item.CLink = CLink;
				
			item.CPic = CPic;
				
			item.CStatus = CStatus;
				
			item.CStateFk = CStateFk;
				
	        item.Save(UserName);
	    }
    }
}
