using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblDoctorImage
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblDoctorImageController
    {
        // Preload our schema..
        TblDoctorImage thisSchemaLoad = new TblDoctorImage();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblDoctorImageCollection FetchAll()
        {
            TblDoctorImageCollection coll = new TblDoctorImageCollection();
            Query qry = new Query(TblDoctorImage.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblDoctorImageCollection FetchByID(object Id)
        {
            TblDoctorImageCollection coll = new TblDoctorImageCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblDoctorImageCollection FetchByQuery(Query qry)
        {
            TblDoctorImageCollection coll = new TblDoctorImageCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblDoctorImage.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblDoctorImage.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string DPicture,int? DDoctorFk)
	    {
		    TblDoctorImage item = new TblDoctorImage();
		    
            item.DPicture = DPicture;
            
            item.DDoctorFk = DDoctorFk;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string DPicture,int? DDoctorFk)
	    {
		    TblDoctorImage item = new TblDoctorImage();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.DPicture = DPicture;
				
			item.DDoctorFk = DDoctorFk;
				
	        item.Save(UserName);
	    }
    }
}
