using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblDoctor class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblDoctorCollection : ActiveList<TblDoctor, TblDoctorCollection>
	{	   
		public TblDoctorCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblDoctorCollection</returns>
		public TblDoctorCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblDoctor o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblDoctors table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblDoctor : ActiveRecord<TblDoctor>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblDoctor()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblDoctor(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblDoctor(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblDoctor(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblDoctors", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarDName = new TableSchema.TableColumn(schema);
				colvarDName.ColumnName = "dName";
				colvarDName.DataType = DbType.String;
				colvarDName.MaxLength = 200;
				colvarDName.AutoIncrement = false;
				colvarDName.IsNullable = true;
				colvarDName.IsPrimaryKey = false;
				colvarDName.IsForeignKey = false;
				colvarDName.IsReadOnly = false;
				colvarDName.DefaultSetting = @"";
				colvarDName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDName);
				
				TableSchema.TableColumn colvarDBranchFk = new TableSchema.TableColumn(schema);
				colvarDBranchFk.ColumnName = "dBranchFk";
				colvarDBranchFk.DataType = DbType.Int32;
				colvarDBranchFk.MaxLength = 0;
				colvarDBranchFk.AutoIncrement = false;
				colvarDBranchFk.IsNullable = true;
				colvarDBranchFk.IsPrimaryKey = false;
				colvarDBranchFk.IsForeignKey = false;
				colvarDBranchFk.IsReadOnly = false;
				colvarDBranchFk.DefaultSetting = @"";
				colvarDBranchFk.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDBranchFk);
				
				TableSchema.TableColumn colvarDProfileImg = new TableSchema.TableColumn(schema);
				colvarDProfileImg.ColumnName = "dProfileImg";
				colvarDProfileImg.DataType = DbType.String;
				colvarDProfileImg.MaxLength = 250;
				colvarDProfileImg.AutoIncrement = false;
				colvarDProfileImg.IsNullable = true;
				colvarDProfileImg.IsPrimaryKey = false;
				colvarDProfileImg.IsForeignKey = false;
				colvarDProfileImg.IsReadOnly = false;
				colvarDProfileImg.DefaultSetting = @"";
				colvarDProfileImg.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDProfileImg);
				
				TableSchema.TableColumn colvarDImg = new TableSchema.TableColumn(schema);
				colvarDImg.ColumnName = "dImg";
				colvarDImg.DataType = DbType.String;
				colvarDImg.MaxLength = 250;
				colvarDImg.AutoIncrement = false;
				colvarDImg.IsNullable = true;
				colvarDImg.IsPrimaryKey = false;
				colvarDImg.IsForeignKey = false;
				colvarDImg.IsReadOnly = false;
				colvarDImg.DefaultSetting = @"";
				colvarDImg.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDImg);
				
				TableSchema.TableColumn colvarDDes = new TableSchema.TableColumn(schema);
				colvarDDes.ColumnName = "dDes";
				colvarDDes.DataType = DbType.String;
				colvarDDes.MaxLength = 1073741823;
				colvarDDes.AutoIncrement = false;
				colvarDDes.IsNullable = true;
				colvarDDes.IsPrimaryKey = false;
				colvarDDes.IsForeignKey = false;
				colvarDDes.IsReadOnly = false;
				colvarDDes.DefaultSetting = @"";
				colvarDDes.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDDes);
				
				TableSchema.TableColumn colvarDInstagram = new TableSchema.TableColumn(schema);
				colvarDInstagram.ColumnName = "dInstagram";
				colvarDInstagram.DataType = DbType.String;
				colvarDInstagram.MaxLength = 50;
				colvarDInstagram.AutoIncrement = false;
				colvarDInstagram.IsNullable = true;
				colvarDInstagram.IsPrimaryKey = false;
				colvarDInstagram.IsForeignKey = false;
				colvarDInstagram.IsReadOnly = false;
				colvarDInstagram.DefaultSetting = @"";
				colvarDInstagram.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDInstagram);
				
				TableSchema.TableColumn colvarDTelegram = new TableSchema.TableColumn(schema);
				colvarDTelegram.ColumnName = "dTelegram";
				colvarDTelegram.DataType = DbType.String;
				colvarDTelegram.MaxLength = 50;
				colvarDTelegram.AutoIncrement = false;
				colvarDTelegram.IsNullable = true;
				colvarDTelegram.IsPrimaryKey = false;
				colvarDTelegram.IsForeignKey = false;
				colvarDTelegram.IsReadOnly = false;
				colvarDTelegram.DefaultSetting = @"";
				colvarDTelegram.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDTelegram);
				
				TableSchema.TableColumn colvarDAparat = new TableSchema.TableColumn(schema);
				colvarDAparat.ColumnName = "dAparat";
				colvarDAparat.DataType = DbType.String;
				colvarDAparat.MaxLength = 50;
				colvarDAparat.AutoIncrement = false;
				colvarDAparat.IsNullable = true;
				colvarDAparat.IsPrimaryKey = false;
				colvarDAparat.IsForeignKey = false;
				colvarDAparat.IsReadOnly = false;
				colvarDAparat.DefaultSetting = @"";
				colvarDAparat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDAparat);
				
				TableSchema.TableColumn colvarDEmail = new TableSchema.TableColumn(schema);
				colvarDEmail.ColumnName = "dEmail";
				colvarDEmail.DataType = DbType.String;
				colvarDEmail.MaxLength = 50;
				colvarDEmail.AutoIncrement = false;
				colvarDEmail.IsNullable = true;
				colvarDEmail.IsPrimaryKey = false;
				colvarDEmail.IsForeignKey = false;
				colvarDEmail.IsReadOnly = false;
				colvarDEmail.DefaultSetting = @"";
				colvarDEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDEmail);
				
				TableSchema.TableColumn colvarDTel = new TableSchema.TableColumn(schema);
				colvarDTel.ColumnName = "dTel";
				colvarDTel.DataType = DbType.String;
				colvarDTel.MaxLength = 50;
				colvarDTel.AutoIncrement = false;
				colvarDTel.IsNullable = true;
				colvarDTel.IsPrimaryKey = false;
				colvarDTel.IsForeignKey = false;
				colvarDTel.IsReadOnly = false;
				colvarDTel.DefaultSetting = @"";
				colvarDTel.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDTel);
				
				TableSchema.TableColumn colvarDMobile = new TableSchema.TableColumn(schema);
				colvarDMobile.ColumnName = "dMobile";
				colvarDMobile.DataType = DbType.String;
				colvarDMobile.MaxLength = 50;
				colvarDMobile.AutoIncrement = false;
				colvarDMobile.IsNullable = true;
				colvarDMobile.IsPrimaryKey = false;
				colvarDMobile.IsForeignKey = false;
				colvarDMobile.IsReadOnly = false;
				colvarDMobile.DefaultSetting = @"";
				colvarDMobile.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDMobile);
				
				TableSchema.TableColumn colvarDVideo = new TableSchema.TableColumn(schema);
				colvarDVideo.ColumnName = "dVideo";
				colvarDVideo.DataType = DbType.String;
				colvarDVideo.MaxLength = 500;
				colvarDVideo.AutoIncrement = false;
				colvarDVideo.IsNullable = true;
				colvarDVideo.IsPrimaryKey = false;
				colvarDVideo.IsForeignKey = false;
				colvarDVideo.IsReadOnly = false;
				colvarDVideo.DefaultSetting = @"";
				colvarDVideo.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDVideo);
				
				TableSchema.TableColumn colvarDVideo2 = new TableSchema.TableColumn(schema);
				colvarDVideo2.ColumnName = "dVideo2";
				colvarDVideo2.DataType = DbType.String;
				colvarDVideo2.MaxLength = 500;
				colvarDVideo2.AutoIncrement = false;
				colvarDVideo2.IsNullable = true;
				colvarDVideo2.IsPrimaryKey = false;
				colvarDVideo2.IsForeignKey = false;
				colvarDVideo2.IsReadOnly = false;
				colvarDVideo2.DefaultSetting = @"";
				colvarDVideo2.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDVideo2);
				
				TableSchema.TableColumn colvarDVideo3 = new TableSchema.TableColumn(schema);
				colvarDVideo3.ColumnName = "dVideo3";
				colvarDVideo3.DataType = DbType.String;
				colvarDVideo3.MaxLength = 500;
				colvarDVideo3.AutoIncrement = false;
				colvarDVideo3.IsNullable = true;
				colvarDVideo3.IsPrimaryKey = false;
				colvarDVideo3.IsForeignKey = false;
				colvarDVideo3.IsReadOnly = false;
				colvarDVideo3.DefaultSetting = @"";
				colvarDVideo3.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDVideo3);
				
				TableSchema.TableColumn colvarDWebsite = new TableSchema.TableColumn(schema);
				colvarDWebsite.ColumnName = "dWebsite";
				colvarDWebsite.DataType = DbType.String;
				colvarDWebsite.MaxLength = 150;
				colvarDWebsite.AutoIncrement = false;
				colvarDWebsite.IsNullable = true;
				colvarDWebsite.IsPrimaryKey = false;
				colvarDWebsite.IsForeignKey = false;
				colvarDWebsite.IsReadOnly = false;
				colvarDWebsite.DefaultSetting = @"";
				colvarDWebsite.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDWebsite);
				
				TableSchema.TableColumn colvarDSpecialty = new TableSchema.TableColumn(schema);
				colvarDSpecialty.ColumnName = "dSpecialty";
				colvarDSpecialty.DataType = DbType.String;
				colvarDSpecialty.MaxLength = 250;
				colvarDSpecialty.AutoIncrement = false;
				colvarDSpecialty.IsNullable = true;
				colvarDSpecialty.IsPrimaryKey = false;
				colvarDSpecialty.IsForeignKey = false;
				colvarDSpecialty.IsReadOnly = false;
				colvarDSpecialty.DefaultSetting = @"";
				colvarDSpecialty.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDSpecialty);
				
				TableSchema.TableColumn colvarDStateFk = new TableSchema.TableColumn(schema);
				colvarDStateFk.ColumnName = "dStateFk";
				colvarDStateFk.DataType = DbType.Int32;
				colvarDStateFk.MaxLength = 0;
				colvarDStateFk.AutoIncrement = false;
				colvarDStateFk.IsNullable = true;
				colvarDStateFk.IsPrimaryKey = false;
				colvarDStateFk.IsForeignKey = false;
				colvarDStateFk.IsReadOnly = false;
				colvarDStateFk.DefaultSetting = @"";
				colvarDStateFk.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDStateFk);
				
				TableSchema.TableColumn colvarDCityFk = new TableSchema.TableColumn(schema);
				colvarDCityFk.ColumnName = "dCityFk";
				colvarDCityFk.DataType = DbType.Int32;
				colvarDCityFk.MaxLength = 0;
				colvarDCityFk.AutoIncrement = false;
				colvarDCityFk.IsNullable = true;
				colvarDCityFk.IsPrimaryKey = false;
				colvarDCityFk.IsForeignKey = false;
				colvarDCityFk.IsReadOnly = false;
				colvarDCityFk.DefaultSetting = @"";
				colvarDCityFk.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDCityFk);
				
				TableSchema.TableColumn colvarDStatus = new TableSchema.TableColumn(schema);
				colvarDStatus.ColumnName = "dStatus";
				colvarDStatus.DataType = DbType.Byte;
				colvarDStatus.MaxLength = 0;
				colvarDStatus.AutoIncrement = false;
				colvarDStatus.IsNullable = true;
				colvarDStatus.IsPrimaryKey = false;
				colvarDStatus.IsForeignKey = false;
				colvarDStatus.IsReadOnly = false;
				colvarDStatus.DefaultSetting = @"";
				colvarDStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDStatus);
				
				TableSchema.TableColumn colvarDIsDeleted = new TableSchema.TableColumn(schema);
				colvarDIsDeleted.ColumnName = "dIsDeleted";
				colvarDIsDeleted.DataType = DbType.Boolean;
				colvarDIsDeleted.MaxLength = 0;
				colvarDIsDeleted.AutoIncrement = false;
				colvarDIsDeleted.IsNullable = true;
				colvarDIsDeleted.IsPrimaryKey = false;
				colvarDIsDeleted.IsForeignKey = false;
				colvarDIsDeleted.IsReadOnly = false;
				colvarDIsDeleted.DefaultSetting = @"";
				colvarDIsDeleted.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDIsDeleted);
				
				TableSchema.TableColumn colvarDSaveDate = new TableSchema.TableColumn(schema);
				colvarDSaveDate.ColumnName = "dSaveDate";
				colvarDSaveDate.DataType = DbType.DateTime;
				colvarDSaveDate.MaxLength = 0;
				colvarDSaveDate.AutoIncrement = false;
				colvarDSaveDate.IsNullable = true;
				colvarDSaveDate.IsPrimaryKey = false;
				colvarDSaveDate.IsForeignKey = false;
				colvarDSaveDate.IsReadOnly = false;
				colvarDSaveDate.DefaultSetting = @"";
				colvarDSaveDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDSaveDate);
				
				TableSchema.TableColumn colvarDEndDate = new TableSchema.TableColumn(schema);
				colvarDEndDate.ColumnName = "dEndDate";
				colvarDEndDate.DataType = DbType.DateTime;
				colvarDEndDate.MaxLength = 0;
				colvarDEndDate.AutoIncrement = false;
				colvarDEndDate.IsNullable = true;
				colvarDEndDate.IsPrimaryKey = false;
				colvarDEndDate.IsForeignKey = false;
				colvarDEndDate.IsReadOnly = false;
				colvarDEndDate.DefaultSetting = @"";
				colvarDEndDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDEndDate);
				
				TableSchema.TableColumn colvarDKeyword = new TableSchema.TableColumn(schema);
				colvarDKeyword.ColumnName = "dKeyword";
				colvarDKeyword.DataType = DbType.String;
				colvarDKeyword.MaxLength = 4000;
				colvarDKeyword.AutoIncrement = false;
				colvarDKeyword.IsNullable = true;
				colvarDKeyword.IsPrimaryKey = false;
				colvarDKeyword.IsForeignKey = false;
				colvarDKeyword.IsReadOnly = false;
				colvarDKeyword.DefaultSetting = @"";
				colvarDKeyword.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDKeyword);
				
				TableSchema.TableColumn colvarDNote = new TableSchema.TableColumn(schema);
				colvarDNote.ColumnName = "dNote";
				colvarDNote.DataType = DbType.String;
				colvarDNote.MaxLength = -1;
				colvarDNote.AutoIncrement = false;
				colvarDNote.IsNullable = true;
				colvarDNote.IsPrimaryKey = false;
				colvarDNote.IsForeignKey = false;
				colvarDNote.IsReadOnly = false;
				colvarDNote.DefaultSetting = @"";
				colvarDNote.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDNote);
				
				TableSchema.TableColumn colvarDAddress = new TableSchema.TableColumn(schema);
				colvarDAddress.ColumnName = "dAddress";
				colvarDAddress.DataType = DbType.String;
				colvarDAddress.MaxLength = 300;
				colvarDAddress.AutoIncrement = false;
				colvarDAddress.IsNullable = true;
				colvarDAddress.IsPrimaryKey = false;
				colvarDAddress.IsForeignKey = false;
				colvarDAddress.IsReadOnly = false;
				colvarDAddress.DefaultSetting = @"";
				colvarDAddress.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDAddress);
				
				TableSchema.TableColumn colvarDWorkTime = new TableSchema.TableColumn(schema);
				colvarDWorkTime.ColumnName = "dWorkTime";
				colvarDWorkTime.DataType = DbType.String;
				colvarDWorkTime.MaxLength = 500;
				colvarDWorkTime.AutoIncrement = false;
				colvarDWorkTime.IsNullable = true;
				colvarDWorkTime.IsPrimaryKey = false;
				colvarDWorkTime.IsForeignKey = false;
				colvarDWorkTime.IsReadOnly = false;
				colvarDWorkTime.DefaultSetting = @"";
				colvarDWorkTime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDWorkTime);
				
				TableSchema.TableColumn colvarDLat = new TableSchema.TableColumn(schema);
				colvarDLat.ColumnName = "dLat";
				colvarDLat.DataType = DbType.String;
				colvarDLat.MaxLength = 10;
				colvarDLat.AutoIncrement = false;
				colvarDLat.IsNullable = true;
				colvarDLat.IsPrimaryKey = false;
				colvarDLat.IsForeignKey = false;
				colvarDLat.IsReadOnly = false;
				colvarDLat.DefaultSetting = @"";
				colvarDLat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDLat);
				
				TableSchema.TableColumn colvarDLong = new TableSchema.TableColumn(schema);
				colvarDLong.ColumnName = "dLong";
				colvarDLong.DataType = DbType.String;
				colvarDLong.MaxLength = 10;
				colvarDLong.AutoIncrement = false;
				colvarDLong.IsNullable = true;
				colvarDLong.IsPrimaryKey = false;
				colvarDLong.IsForeignKey = false;
				colvarDLong.IsReadOnly = false;
				colvarDLong.DefaultSetting = @"";
				colvarDLong.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDLong);
				
				TableSchema.TableColumn colvarDPassword = new TableSchema.TableColumn(schema);
				colvarDPassword.ColumnName = "dPassword";
				colvarDPassword.DataType = DbType.String;
				colvarDPassword.MaxLength = 500;
				colvarDPassword.AutoIncrement = false;
				colvarDPassword.IsNullable = true;
				colvarDPassword.IsPrimaryKey = false;
				colvarDPassword.IsForeignKey = false;
				colvarDPassword.IsReadOnly = false;
				colvarDPassword.DefaultSetting = @"";
				colvarDPassword.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDPassword);
				
				TableSchema.TableColumn colvarDUsername = new TableSchema.TableColumn(schema);
				colvarDUsername.ColumnName = "dUsername";
				colvarDUsername.DataType = DbType.String;
				colvarDUsername.MaxLength = 30;
				colvarDUsername.AutoIncrement = false;
				colvarDUsername.IsNullable = true;
				colvarDUsername.IsPrimaryKey = false;
				colvarDUsername.IsForeignKey = false;
				colvarDUsername.IsReadOnly = false;
				colvarDUsername.DefaultSetting = @"";
				colvarDUsername.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDUsername);
				
				TableSchema.TableColumn colvarDDes2 = new TableSchema.TableColumn(schema);
				colvarDDes2.ColumnName = "dDes2";
				colvarDDes2.DataType = DbType.String;
				colvarDDes2.MaxLength = 1073741823;
				colvarDDes2.AutoIncrement = false;
				colvarDDes2.IsNullable = true;
				colvarDDes2.IsPrimaryKey = false;
				colvarDDes2.IsForeignKey = false;
				colvarDDes2.IsReadOnly = false;
				colvarDDes2.DefaultSetting = @"";
				colvarDDes2.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDDes2);
				
				TableSchema.TableColumn colvarDSpecialAd = new TableSchema.TableColumn(schema);
				colvarDSpecialAd.ColumnName = "dSpecialAd";
				colvarDSpecialAd.DataType = DbType.Boolean;
				colvarDSpecialAd.MaxLength = 0;
				colvarDSpecialAd.AutoIncrement = false;
				colvarDSpecialAd.IsNullable = true;
				colvarDSpecialAd.IsPrimaryKey = false;
				colvarDSpecialAd.IsForeignKey = false;
				colvarDSpecialAd.IsReadOnly = false;
				colvarDSpecialAd.DefaultSetting = @"";
				colvarDSpecialAd.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDSpecialAd);
				
				TableSchema.TableColumn colvarDEnName = new TableSchema.TableColumn(schema);
				colvarDEnName.ColumnName = "dEnName";
				colvarDEnName.DataType = DbType.String;
				colvarDEnName.MaxLength = 50;
				colvarDEnName.AutoIncrement = false;
				colvarDEnName.IsNullable = true;
				colvarDEnName.IsPrimaryKey = false;
				colvarDEnName.IsForeignKey = false;
				colvarDEnName.IsReadOnly = false;
				colvarDEnName.DefaultSetting = @"";
				colvarDEnName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDEnName);
				
				TableSchema.TableColumn colvarDEnDes = new TableSchema.TableColumn(schema);
				colvarDEnDes.ColumnName = "dEnDes";
				colvarDEnDes.DataType = DbType.String;
				colvarDEnDes.MaxLength = 1073741823;
				colvarDEnDes.AutoIncrement = false;
				colvarDEnDes.IsNullable = true;
				colvarDEnDes.IsPrimaryKey = false;
				colvarDEnDes.IsForeignKey = false;
				colvarDEnDes.IsReadOnly = false;
				colvarDEnDes.DefaultSetting = @"";
				colvarDEnDes.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDEnDes);
				
				TableSchema.TableColumn colvarDArDes = new TableSchema.TableColumn(schema);
				colvarDArDes.ColumnName = "dArDes";
				colvarDArDes.DataType = DbType.String;
				colvarDArDes.MaxLength = 1073741823;
				colvarDArDes.AutoIncrement = false;
				colvarDArDes.IsNullable = true;
				colvarDArDes.IsPrimaryKey = false;
				colvarDArDes.IsForeignKey = false;
				colvarDArDes.IsReadOnly = false;
				colvarDArDes.DefaultSetting = @"";
				colvarDArDes.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDArDes);
				
				TableSchema.TableColumn colvarDEnSpecialty = new TableSchema.TableColumn(schema);
				colvarDEnSpecialty.ColumnName = "dEnSpecialty";
				colvarDEnSpecialty.DataType = DbType.String;
				colvarDEnSpecialty.MaxLength = 200;
				colvarDEnSpecialty.AutoIncrement = false;
				colvarDEnSpecialty.IsNullable = true;
				colvarDEnSpecialty.IsPrimaryKey = false;
				colvarDEnSpecialty.IsForeignKey = false;
				colvarDEnSpecialty.IsReadOnly = false;
				colvarDEnSpecialty.DefaultSetting = @"";
				colvarDEnSpecialty.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDEnSpecialty);
				
				TableSchema.TableColumn colvarDArSpecialty = new TableSchema.TableColumn(schema);
				colvarDArSpecialty.ColumnName = "dArSpecialty";
				colvarDArSpecialty.DataType = DbType.String;
				colvarDArSpecialty.MaxLength = 200;
				colvarDArSpecialty.AutoIncrement = false;
				colvarDArSpecialty.IsNullable = true;
				colvarDArSpecialty.IsPrimaryKey = false;
				colvarDArSpecialty.IsForeignKey = false;
				colvarDArSpecialty.IsReadOnly = false;
				colvarDArSpecialty.DefaultSetting = @"";
				colvarDArSpecialty.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDArSpecialty);
				
				TableSchema.TableColumn colvarDEnAddress = new TableSchema.TableColumn(schema);
				colvarDEnAddress.ColumnName = "dEnAddress";
				colvarDEnAddress.DataType = DbType.String;
				colvarDEnAddress.MaxLength = 250;
				colvarDEnAddress.AutoIncrement = false;
				colvarDEnAddress.IsNullable = true;
				colvarDEnAddress.IsPrimaryKey = false;
				colvarDEnAddress.IsForeignKey = false;
				colvarDEnAddress.IsReadOnly = false;
				colvarDEnAddress.DefaultSetting = @"";
				colvarDEnAddress.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDEnAddress);
				
				TableSchema.TableColumn colvarDArAddress = new TableSchema.TableColumn(schema);
				colvarDArAddress.ColumnName = "dArAddress";
				colvarDArAddress.DataType = DbType.String;
				colvarDArAddress.MaxLength = 250;
				colvarDArAddress.AutoIncrement = false;
				colvarDArAddress.IsNullable = true;
				colvarDArAddress.IsPrimaryKey = false;
				colvarDArAddress.IsForeignKey = false;
				colvarDArAddress.IsReadOnly = false;
				colvarDArAddress.DefaultSetting = @"";
				colvarDArAddress.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDArAddress);
				
				TableSchema.TableColumn colvarDEnWorkTime = new TableSchema.TableColumn(schema);
				colvarDEnWorkTime.ColumnName = "dEnWorkTime";
				colvarDEnWorkTime.DataType = DbType.String;
				colvarDEnWorkTime.MaxLength = 100;
				colvarDEnWorkTime.AutoIncrement = false;
				colvarDEnWorkTime.IsNullable = true;
				colvarDEnWorkTime.IsPrimaryKey = false;
				colvarDEnWorkTime.IsForeignKey = false;
				colvarDEnWorkTime.IsReadOnly = false;
				colvarDEnWorkTime.DefaultSetting = @"";
				colvarDEnWorkTime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDEnWorkTime);
				
				TableSchema.TableColumn colvarDArWorkTime = new TableSchema.TableColumn(schema);
				colvarDArWorkTime.ColumnName = "dArWorkTime";
				colvarDArWorkTime.DataType = DbType.String;
				colvarDArWorkTime.MaxLength = 100;
				colvarDArWorkTime.AutoIncrement = false;
				colvarDArWorkTime.IsNullable = true;
				colvarDArWorkTime.IsPrimaryKey = false;
				colvarDArWorkTime.IsForeignKey = false;
				colvarDArWorkTime.IsReadOnly = false;
				colvarDArWorkTime.DefaultSetting = @"";
				colvarDArWorkTime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDArWorkTime);
				
				TableSchema.TableColumn colvarDArName = new TableSchema.TableColumn(schema);
				colvarDArName.ColumnName = "dArName";
				colvarDArName.DataType = DbType.String;
				colvarDArName.MaxLength = 200;
				colvarDArName.AutoIncrement = false;
				colvarDArName.IsNullable = true;
				colvarDArName.IsPrimaryKey = false;
				colvarDArName.IsForeignKey = false;
				colvarDArName.IsReadOnly = false;
				colvarDArName.DefaultSetting = @"";
				colvarDArName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDArName);
				
				TableSchema.TableColumn colvarDWhatsapp = new TableSchema.TableColumn(schema);
				colvarDWhatsapp.ColumnName = "dWhatsapp";
				colvarDWhatsapp.DataType = DbType.String;
				colvarDWhatsapp.MaxLength = 50;
				colvarDWhatsapp.AutoIncrement = false;
				colvarDWhatsapp.IsNullable = true;
				colvarDWhatsapp.IsPrimaryKey = false;
				colvarDWhatsapp.IsForeignKey = false;
				colvarDWhatsapp.IsReadOnly = false;
				colvarDWhatsapp.DefaultSetting = @"";
				colvarDWhatsapp.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDWhatsapp);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblDoctors",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("DName")]
		[Bindable(true)]
        [DataMember]
		public string DName 
		{
			get { return GetColumnValue<string>(Columns.DName); }
			set { SetColumnValue(Columns.DName, value); }
		}
		  
		[XmlAttribute("DBranchFk")]
		[Bindable(true)]
        [DataMember]
		public int? DBranchFk 
		{
			get { return GetColumnValue<int?>(Columns.DBranchFk); }
			set { SetColumnValue(Columns.DBranchFk, value); }
		}
		  
		[XmlAttribute("DProfileImg")]
		[Bindable(true)]
        [DataMember]
		public string DProfileImg 
		{
			get { return GetColumnValue<string>(Columns.DProfileImg); }
			set { SetColumnValue(Columns.DProfileImg, value); }
		}
		  
		[XmlAttribute("DImg")]
		[Bindable(true)]
        [DataMember]
		public string DImg 
		{
			get { return GetColumnValue<string>(Columns.DImg); }
			set { SetColumnValue(Columns.DImg, value); }
		}
		  
		[XmlAttribute("DDes")]
		[Bindable(true)]
        [DataMember]
		public string DDes 
		{
			get { return GetColumnValue<string>(Columns.DDes); }
			set { SetColumnValue(Columns.DDes, value); }
		}
		  
		[XmlAttribute("DInstagram")]
		[Bindable(true)]
        [DataMember]
		public string DInstagram 
		{
			get { return GetColumnValue<string>(Columns.DInstagram); }
			set { SetColumnValue(Columns.DInstagram, value); }
		}
		  
		[XmlAttribute("DTelegram")]
		[Bindable(true)]
        [DataMember]
		public string DTelegram 
		{
			get { return GetColumnValue<string>(Columns.DTelegram); }
			set { SetColumnValue(Columns.DTelegram, value); }
		}
		  
		[XmlAttribute("DAparat")]
		[Bindable(true)]
        [DataMember]
		public string DAparat 
		{
			get { return GetColumnValue<string>(Columns.DAparat); }
			set { SetColumnValue(Columns.DAparat, value); }
		}
		  
		[XmlAttribute("DEmail")]
		[Bindable(true)]
        [DataMember]
		public string DEmail 
		{
			get { return GetColumnValue<string>(Columns.DEmail); }
			set { SetColumnValue(Columns.DEmail, value); }
		}
		  
		[XmlAttribute("DTel")]
		[Bindable(true)]
        [DataMember]
		public string DTel 
		{
			get { return GetColumnValue<string>(Columns.DTel); }
			set { SetColumnValue(Columns.DTel, value); }
		}
		  
		[XmlAttribute("DMobile")]
		[Bindable(true)]
        [DataMember]
		public string DMobile 
		{
			get { return GetColumnValue<string>(Columns.DMobile); }
			set { SetColumnValue(Columns.DMobile, value); }
		}
		  
		[XmlAttribute("DVideo")]
		[Bindable(true)]
        [DataMember]
		public string DVideo 
		{
			get { return GetColumnValue<string>(Columns.DVideo); }
			set { SetColumnValue(Columns.DVideo, value); }
		}
		  
		[XmlAttribute("DVideo2")]
		[Bindable(true)]
        [DataMember]
		public string DVideo2 
		{
			get { return GetColumnValue<string>(Columns.DVideo2); }
			set { SetColumnValue(Columns.DVideo2, value); }
		}
		  
		[XmlAttribute("DVideo3")]
		[Bindable(true)]
        [DataMember]
		public string DVideo3 
		{
			get { return GetColumnValue<string>(Columns.DVideo3); }
			set { SetColumnValue(Columns.DVideo3, value); }
		}
		  
		[XmlAttribute("DWebsite")]
		[Bindable(true)]
        [DataMember]
		public string DWebsite 
		{
			get { return GetColumnValue<string>(Columns.DWebsite); }
			set { SetColumnValue(Columns.DWebsite, value); }
		}
		  
		[XmlAttribute("DSpecialty")]
		[Bindable(true)]
        [DataMember]
		public string DSpecialty 
		{
			get { return GetColumnValue<string>(Columns.DSpecialty); }
			set { SetColumnValue(Columns.DSpecialty, value); }
		}
		  
		[XmlAttribute("DStateFk")]
		[Bindable(true)]
        [DataMember]
		public int? DStateFk 
		{
			get { return GetColumnValue<int?>(Columns.DStateFk); }
			set { SetColumnValue(Columns.DStateFk, value); }
		}
		  
		[XmlAttribute("DCityFk")]
		[Bindable(true)]
        [DataMember]
		public int? DCityFk 
		{
			get { return GetColumnValue<int?>(Columns.DCityFk); }
			set { SetColumnValue(Columns.DCityFk, value); }
		}
		  
		[XmlAttribute("DStatus")]
		[Bindable(true)]
        [DataMember]
		public byte? DStatus 
		{
			get { return GetColumnValue<byte?>(Columns.DStatus); }
			set { SetColumnValue(Columns.DStatus, value); }
		}
		  
		[XmlAttribute("DIsDeleted")]
		[Bindable(true)]
        [DataMember]
		public bool? DIsDeleted 
		{
			get { return GetColumnValue<bool?>(Columns.DIsDeleted); }
			set { SetColumnValue(Columns.DIsDeleted, value); }
		}
		  
		[XmlAttribute("DSaveDate")]
		[Bindable(true)]
        [DataMember]
		public DateTime? DSaveDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.DSaveDate); }
			set { SetColumnValue(Columns.DSaveDate, value); }
		}
		  
		[XmlAttribute("DEndDate")]
		[Bindable(true)]
        [DataMember]
		public DateTime? DEndDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.DEndDate); }
			set { SetColumnValue(Columns.DEndDate, value); }
		}
		  
		[XmlAttribute("DKeyword")]
		[Bindable(true)]
        [DataMember]
		public string DKeyword 
		{
			get { return GetColumnValue<string>(Columns.DKeyword); }
			set { SetColumnValue(Columns.DKeyword, value); }
		}
		  
		[XmlAttribute("DNote")]
		[Bindable(true)]
        [DataMember]
		public string DNote 
		{
			get { return GetColumnValue<string>(Columns.DNote); }
			set { SetColumnValue(Columns.DNote, value); }
		}
		  
		[XmlAttribute("DAddress")]
		[Bindable(true)]
        [DataMember]
		public string DAddress 
		{
			get { return GetColumnValue<string>(Columns.DAddress); }
			set { SetColumnValue(Columns.DAddress, value); }
		}
		  
		[XmlAttribute("DWorkTime")]
		[Bindable(true)]
        [DataMember]
		public string DWorkTime 
		{
			get { return GetColumnValue<string>(Columns.DWorkTime); }
			set { SetColumnValue(Columns.DWorkTime, value); }
		}
		  
		[XmlAttribute("DLat")]
		[Bindable(true)]
        [DataMember]
		public string DLat 
		{
			get { return GetColumnValue<string>(Columns.DLat); }
			set { SetColumnValue(Columns.DLat, value); }
		}
		  
		[XmlAttribute("DLong")]
		[Bindable(true)]
        [DataMember]
		public string DLong 
		{
			get { return GetColumnValue<string>(Columns.DLong); }
			set { SetColumnValue(Columns.DLong, value); }
		}
		  
		[XmlAttribute("DPassword")]
		[Bindable(true)]
        [DataMember]
		public string DPassword 
		{
			get { return GetColumnValue<string>(Columns.DPassword); }
			set { SetColumnValue(Columns.DPassword, value); }
		}
		  
		[XmlAttribute("DUsername")]
		[Bindable(true)]
        [DataMember]
		public string DUsername 
		{
			get { return GetColumnValue<string>(Columns.DUsername); }
			set { SetColumnValue(Columns.DUsername, value); }
		}
		  
		[XmlAttribute("DDes2")]
		[Bindable(true)]
        [DataMember]
		public string DDes2 
		{
			get { return GetColumnValue<string>(Columns.DDes2); }
			set { SetColumnValue(Columns.DDes2, value); }
		}
		  
		[XmlAttribute("DSpecialAd")]
		[Bindable(true)]
        [DataMember]
		public bool? DSpecialAd 
		{
			get { return GetColumnValue<bool?>(Columns.DSpecialAd); }
			set { SetColumnValue(Columns.DSpecialAd, value); }
		}
		  
		[XmlAttribute("DEnName")]
		[Bindable(true)]
        [DataMember]
		public string DEnName 
		{
			get { return GetColumnValue<string>(Columns.DEnName); }
			set { SetColumnValue(Columns.DEnName, value); }
		}
		  
		[XmlAttribute("DEnDes")]
		[Bindable(true)]
        [DataMember]
		public string DEnDes 
		{
			get { return GetColumnValue<string>(Columns.DEnDes); }
			set { SetColumnValue(Columns.DEnDes, value); }
		}
		  
		[XmlAttribute("DArDes")]
		[Bindable(true)]
        [DataMember]
		public string DArDes 
		{
			get { return GetColumnValue<string>(Columns.DArDes); }
			set { SetColumnValue(Columns.DArDes, value); }
		}
		  
		[XmlAttribute("DEnSpecialty")]
		[Bindable(true)]
        [DataMember]
		public string DEnSpecialty 
		{
			get { return GetColumnValue<string>(Columns.DEnSpecialty); }
			set { SetColumnValue(Columns.DEnSpecialty, value); }
		}
		  
		[XmlAttribute("DArSpecialty")]
		[Bindable(true)]
        [DataMember]
		public string DArSpecialty 
		{
			get { return GetColumnValue<string>(Columns.DArSpecialty); }
			set { SetColumnValue(Columns.DArSpecialty, value); }
		}
		  
		[XmlAttribute("DEnAddress")]
		[Bindable(true)]
        [DataMember]
		public string DEnAddress 
		{
			get { return GetColumnValue<string>(Columns.DEnAddress); }
			set { SetColumnValue(Columns.DEnAddress, value); }
		}
		  
		[XmlAttribute("DArAddress")]
		[Bindable(true)]
        [DataMember]
		public string DArAddress 
		{
			get { return GetColumnValue<string>(Columns.DArAddress); }
			set { SetColumnValue(Columns.DArAddress, value); }
		}
		  
		[XmlAttribute("DEnWorkTime")]
		[Bindable(true)]
        [DataMember]
		public string DEnWorkTime 
		{
			get { return GetColumnValue<string>(Columns.DEnWorkTime); }
			set { SetColumnValue(Columns.DEnWorkTime, value); }
		}
		  
		[XmlAttribute("DArWorkTime")]
		[Bindable(true)]
        [DataMember]
		public string DArWorkTime 
		{
			get { return GetColumnValue<string>(Columns.DArWorkTime); }
			set { SetColumnValue(Columns.DArWorkTime, value); }
		}
		  
		[XmlAttribute("DArName")]
		[Bindable(true)]
        [DataMember]
		public string DArName 
		{
			get { return GetColumnValue<string>(Columns.DArName); }
			set { SetColumnValue(Columns.DArName, value); }
		}
		  
		[XmlAttribute("DWhatsapp")]
		[Bindable(true)]
        [DataMember]
		public string DWhatsapp 
		{
			get { return GetColumnValue<string>(Columns.DWhatsapp); }
			set { SetColumnValue(Columns.DWhatsapp, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varDName,int? varDBranchFk,string varDProfileImg,string varDImg,string varDDes,string varDInstagram,string varDTelegram,string varDAparat,string varDEmail,string varDTel,string varDMobile,string varDVideo,string varDVideo2,string varDVideo3,string varDWebsite,string varDSpecialty,int? varDStateFk,int? varDCityFk,byte? varDStatus,bool? varDIsDeleted,DateTime? varDSaveDate,DateTime? varDEndDate,string varDKeyword,string varDNote,string varDAddress,string varDWorkTime,string varDLat,string varDLong,string varDPassword,string varDUsername,string varDDes2,bool? varDSpecialAd,string varDEnName,string varDEnDes,string varDArDes,string varDEnSpecialty,string varDArSpecialty,string varDEnAddress,string varDArAddress,string varDEnWorkTime,string varDArWorkTime,string varDArName,string varDWhatsapp)
		{
			TblDoctor item = new TblDoctor();
			
			item.DName = varDName;
			
			item.DBranchFk = varDBranchFk;
			
			item.DProfileImg = varDProfileImg;
			
			item.DImg = varDImg;
			
			item.DDes = varDDes;
			
			item.DInstagram = varDInstagram;
			
			item.DTelegram = varDTelegram;
			
			item.DAparat = varDAparat;
			
			item.DEmail = varDEmail;
			
			item.DTel = varDTel;
			
			item.DMobile = varDMobile;
			
			item.DVideo = varDVideo;
			
			item.DVideo2 = varDVideo2;
			
			item.DVideo3 = varDVideo3;
			
			item.DWebsite = varDWebsite;
			
			item.DSpecialty = varDSpecialty;
			
			item.DStateFk = varDStateFk;
			
			item.DCityFk = varDCityFk;
			
			item.DStatus = varDStatus;
			
			item.DIsDeleted = varDIsDeleted;
			
			item.DSaveDate = varDSaveDate;
			
			item.DEndDate = varDEndDate;
			
			item.DKeyword = varDKeyword;
			
			item.DNote = varDNote;
			
			item.DAddress = varDAddress;
			
			item.DWorkTime = varDWorkTime;
			
			item.DLat = varDLat;
			
			item.DLong = varDLong;
			
			item.DPassword = varDPassword;
			
			item.DUsername = varDUsername;
			
			item.DDes2 = varDDes2;
			
			item.DSpecialAd = varDSpecialAd;
			
			item.DEnName = varDEnName;
			
			item.DEnDes = varDEnDes;
			
			item.DArDes = varDArDes;
			
			item.DEnSpecialty = varDEnSpecialty;
			
			item.DArSpecialty = varDArSpecialty;
			
			item.DEnAddress = varDEnAddress;
			
			item.DArAddress = varDArAddress;
			
			item.DEnWorkTime = varDEnWorkTime;
			
			item.DArWorkTime = varDArWorkTime;
			
			item.DArName = varDArName;
			
			item.DWhatsapp = varDWhatsapp;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varDName,int? varDBranchFk,string varDProfileImg,string varDImg,string varDDes,string varDInstagram,string varDTelegram,string varDAparat,string varDEmail,string varDTel,string varDMobile,string varDVideo,string varDVideo2,string varDVideo3,string varDWebsite,string varDSpecialty,int? varDStateFk,int? varDCityFk,byte? varDStatus,bool? varDIsDeleted,DateTime? varDSaveDate,DateTime? varDEndDate,string varDKeyword,string varDNote,string varDAddress,string varDWorkTime,string varDLat,string varDLong,string varDPassword,string varDUsername,string varDDes2,bool? varDSpecialAd,string varDEnName,string varDEnDes,string varDArDes,string varDEnSpecialty,string varDArSpecialty,string varDEnAddress,string varDArAddress,string varDEnWorkTime,string varDArWorkTime,string varDArName,string varDWhatsapp)
		{
			TblDoctor item = new TblDoctor();
			
				item.Id = varId;
			
				item.DName = varDName;
			
				item.DBranchFk = varDBranchFk;
			
				item.DProfileImg = varDProfileImg;
			
				item.DImg = varDImg;
			
				item.DDes = varDDes;
			
				item.DInstagram = varDInstagram;
			
				item.DTelegram = varDTelegram;
			
				item.DAparat = varDAparat;
			
				item.DEmail = varDEmail;
			
				item.DTel = varDTel;
			
				item.DMobile = varDMobile;
			
				item.DVideo = varDVideo;
			
				item.DVideo2 = varDVideo2;
			
				item.DVideo3 = varDVideo3;
			
				item.DWebsite = varDWebsite;
			
				item.DSpecialty = varDSpecialty;
			
				item.DStateFk = varDStateFk;
			
				item.DCityFk = varDCityFk;
			
				item.DStatus = varDStatus;
			
				item.DIsDeleted = varDIsDeleted;
			
				item.DSaveDate = varDSaveDate;
			
				item.DEndDate = varDEndDate;
			
				item.DKeyword = varDKeyword;
			
				item.DNote = varDNote;
			
				item.DAddress = varDAddress;
			
				item.DWorkTime = varDWorkTime;
			
				item.DLat = varDLat;
			
				item.DLong = varDLong;
			
				item.DPassword = varDPassword;
			
				item.DUsername = varDUsername;
			
				item.DDes2 = varDDes2;
			
				item.DSpecialAd = varDSpecialAd;
			
				item.DEnName = varDEnName;
			
				item.DEnDes = varDEnDes;
			
				item.DArDes = varDArDes;
			
				item.DEnSpecialty = varDEnSpecialty;
			
				item.DArSpecialty = varDArSpecialty;
			
				item.DEnAddress = varDEnAddress;
			
				item.DArAddress = varDArAddress;
			
				item.DEnWorkTime = varDEnWorkTime;
			
				item.DArWorkTime = varDArWorkTime;
			
				item.DArName = varDArName;
			
				item.DWhatsapp = varDWhatsapp;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn DNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn DBranchFkColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn DProfileImgColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn DImgColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn DDesColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn DInstagramColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn DTelegramColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn DAparatColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn DEmailColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn DTelColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn DMobileColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn DVideoColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn DVideo2Column
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        public static TableSchema.TableColumn DVideo3Column
        {
            get { return Schema.Columns[14]; }
        }
        
        
        
        public static TableSchema.TableColumn DWebsiteColumn
        {
            get { return Schema.Columns[15]; }
        }
        
        
        
        public static TableSchema.TableColumn DSpecialtyColumn
        {
            get { return Schema.Columns[16]; }
        }
        
        
        
        public static TableSchema.TableColumn DStateFkColumn
        {
            get { return Schema.Columns[17]; }
        }
        
        
        
        public static TableSchema.TableColumn DCityFkColumn
        {
            get { return Schema.Columns[18]; }
        }
        
        
        
        public static TableSchema.TableColumn DStatusColumn
        {
            get { return Schema.Columns[19]; }
        }
        
        
        
        public static TableSchema.TableColumn DIsDeletedColumn
        {
            get { return Schema.Columns[20]; }
        }
        
        
        
        public static TableSchema.TableColumn DSaveDateColumn
        {
            get { return Schema.Columns[21]; }
        }
        
        
        
        public static TableSchema.TableColumn DEndDateColumn
        {
            get { return Schema.Columns[22]; }
        }
        
        
        
        public static TableSchema.TableColumn DKeywordColumn
        {
            get { return Schema.Columns[23]; }
        }
        
        
        
        public static TableSchema.TableColumn DNoteColumn
        {
            get { return Schema.Columns[24]; }
        }
        
        
        
        public static TableSchema.TableColumn DAddressColumn
        {
            get { return Schema.Columns[25]; }
        }
        
        
        
        public static TableSchema.TableColumn DWorkTimeColumn
        {
            get { return Schema.Columns[26]; }
        }
        
        
        
        public static TableSchema.TableColumn DLatColumn
        {
            get { return Schema.Columns[27]; }
        }
        
        
        
        public static TableSchema.TableColumn DLongColumn
        {
            get { return Schema.Columns[28]; }
        }
        
        
        
        public static TableSchema.TableColumn DPasswordColumn
        {
            get { return Schema.Columns[29]; }
        }
        
        
        
        public static TableSchema.TableColumn DUsernameColumn
        {
            get { return Schema.Columns[30]; }
        }
        
        
        
        public static TableSchema.TableColumn DDes2Column
        {
            get { return Schema.Columns[31]; }
        }
        
        
        
        public static TableSchema.TableColumn DSpecialAdColumn
        {
            get { return Schema.Columns[32]; }
        }
        
        
        
        public static TableSchema.TableColumn DEnNameColumn
        {
            get { return Schema.Columns[33]; }
        }
        
        
        
        public static TableSchema.TableColumn DEnDesColumn
        {
            get { return Schema.Columns[34]; }
        }
        
        
        
        public static TableSchema.TableColumn DArDesColumn
        {
            get { return Schema.Columns[35]; }
        }
        
        
        
        public static TableSchema.TableColumn DEnSpecialtyColumn
        {
            get { return Schema.Columns[36]; }
        }
        
        
        
        public static TableSchema.TableColumn DArSpecialtyColumn
        {
            get { return Schema.Columns[37]; }
        }
        
        
        
        public static TableSchema.TableColumn DEnAddressColumn
        {
            get { return Schema.Columns[38]; }
        }
        
        
        
        public static TableSchema.TableColumn DArAddressColumn
        {
            get { return Schema.Columns[39]; }
        }
        
        
        
        public static TableSchema.TableColumn DEnWorkTimeColumn
        {
            get { return Schema.Columns[40]; }
        }
        
        
        
        public static TableSchema.TableColumn DArWorkTimeColumn
        {
            get { return Schema.Columns[41]; }
        }
        
        
        
        public static TableSchema.TableColumn DArNameColumn
        {
            get { return Schema.Columns[42]; }
        }
        
        
        
        public static TableSchema.TableColumn DWhatsappColumn
        {
            get { return Schema.Columns[43]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string DName = @"dName";
			 public static string DBranchFk = @"dBranchFk";
			 public static string DProfileImg = @"dProfileImg";
			 public static string DImg = @"dImg";
			 public static string DDes = @"dDes";
			 public static string DInstagram = @"dInstagram";
			 public static string DTelegram = @"dTelegram";
			 public static string DAparat = @"dAparat";
			 public static string DEmail = @"dEmail";
			 public static string DTel = @"dTel";
			 public static string DMobile = @"dMobile";
			 public static string DVideo = @"dVideo";
			 public static string DVideo2 = @"dVideo2";
			 public static string DVideo3 = @"dVideo3";
			 public static string DWebsite = @"dWebsite";
			 public static string DSpecialty = @"dSpecialty";
			 public static string DStateFk = @"dStateFk";
			 public static string DCityFk = @"dCityFk";
			 public static string DStatus = @"dStatus";
			 public static string DIsDeleted = @"dIsDeleted";
			 public static string DSaveDate = @"dSaveDate";
			 public static string DEndDate = @"dEndDate";
			 public static string DKeyword = @"dKeyword";
			 public static string DNote = @"dNote";
			 public static string DAddress = @"dAddress";
			 public static string DWorkTime = @"dWorkTime";
			 public static string DLat = @"dLat";
			 public static string DLong = @"dLong";
			 public static string DPassword = @"dPassword";
			 public static string DUsername = @"dUsername";
			 public static string DDes2 = @"dDes2";
			 public static string DSpecialAd = @"dSpecialAd";
			 public static string DEnName = @"dEnName";
			 public static string DEnDes = @"dEnDes";
			 public static string DArDes = @"dArDes";
			 public static string DEnSpecialty = @"dEnSpecialty";
			 public static string DArSpecialty = @"dArSpecialty";
			 public static string DEnAddress = @"dEnAddress";
			 public static string DArAddress = @"dArAddress";
			 public static string DEnWorkTime = @"dEnWorkTime";
			 public static string DArWorkTime = @"dArWorkTime";
			 public static string DArName = @"dArName";
			 public static string DWhatsapp = @"dWhatsapp";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
