using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblDoctorPool class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblDoctorPoolCollection : ActiveList<TblDoctorPool, TblDoctorPoolCollection>
	{	   
		public TblDoctorPoolCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblDoctorPoolCollection</returns>
		public TblDoctorPoolCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblDoctorPool o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblDoctorPool table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblDoctorPool : ActiveRecord<TblDoctorPool>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblDoctorPool()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblDoctorPool(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblDoctorPool(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblDoctorPool(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblDoctorPool", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarPDoctorFk = new TableSchema.TableColumn(schema);
				colvarPDoctorFk.ColumnName = "pDoctorFk";
				colvarPDoctorFk.DataType = DbType.Int32;
				colvarPDoctorFk.MaxLength = 0;
				colvarPDoctorFk.AutoIncrement = false;
				colvarPDoctorFk.IsNullable = true;
				colvarPDoctorFk.IsPrimaryKey = false;
				colvarPDoctorFk.IsForeignKey = false;
				colvarPDoctorFk.IsReadOnly = false;
				colvarPDoctorFk.DefaultSetting = @"";
				colvarPDoctorFk.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPDoctorFk);
				
				TableSchema.TableColumn colvarPSaveDate = new TableSchema.TableColumn(schema);
				colvarPSaveDate.ColumnName = "pSaveDate";
				colvarPSaveDate.DataType = DbType.DateTime;
				colvarPSaveDate.MaxLength = 0;
				colvarPSaveDate.AutoIncrement = false;
				colvarPSaveDate.IsNullable = true;
				colvarPSaveDate.IsPrimaryKey = false;
				colvarPSaveDate.IsForeignKey = false;
				colvarPSaveDate.IsReadOnly = false;
				colvarPSaveDate.DefaultSetting = @"";
				colvarPSaveDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPSaveDate);
				
				TableSchema.TableColumn colvarPName = new TableSchema.TableColumn(schema);
				colvarPName.ColumnName = "pName";
				colvarPName.DataType = DbType.String;
				colvarPName.MaxLength = 50;
				colvarPName.AutoIncrement = false;
				colvarPName.IsNullable = true;
				colvarPName.IsPrimaryKey = false;
				colvarPName.IsForeignKey = false;
				colvarPName.IsReadOnly = false;
				colvarPName.DefaultSetting = @"";
				colvarPName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPName);
				
				TableSchema.TableColumn colvarPTel = new TableSchema.TableColumn(schema);
				colvarPTel.ColumnName = "pTel";
				colvarPTel.DataType = DbType.String;
				colvarPTel.MaxLength = 50;
				colvarPTel.AutoIncrement = false;
				colvarPTel.IsNullable = true;
				colvarPTel.IsPrimaryKey = false;
				colvarPTel.IsForeignKey = false;
				colvarPTel.IsReadOnly = false;
				colvarPTel.DefaultSetting = @"";
				colvarPTel.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPTel);
				
				TableSchema.TableColumn colvarPStatus = new TableSchema.TableColumn(schema);
				colvarPStatus.ColumnName = "pStatus";
				colvarPStatus.DataType = DbType.Byte;
				colvarPStatus.MaxLength = 0;
				colvarPStatus.AutoIncrement = false;
				colvarPStatus.IsNullable = true;
				colvarPStatus.IsPrimaryKey = false;
				colvarPStatus.IsForeignKey = false;
				colvarPStatus.IsReadOnly = false;
				colvarPStatus.DefaultSetting = @"";
				colvarPStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPStatus);
				
				TableSchema.TableColumn colvarPDes = new TableSchema.TableColumn(schema);
				colvarPDes.ColumnName = "pDes";
				colvarPDes.DataType = DbType.String;
				colvarPDes.MaxLength = 2000;
				colvarPDes.AutoIncrement = false;
				colvarPDes.IsNullable = true;
				colvarPDes.IsPrimaryKey = false;
				colvarPDes.IsForeignKey = false;
				colvarPDes.IsReadOnly = false;
				colvarPDes.DefaultSetting = @"";
				colvarPDes.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPDes);
				
				TableSchema.TableColumn colvarPPersianDate = new TableSchema.TableColumn(schema);
				colvarPPersianDate.ColumnName = "pPersianDate";
				colvarPPersianDate.DataType = DbType.String;
				colvarPPersianDate.MaxLength = 10;
				colvarPPersianDate.AutoIncrement = false;
				colvarPPersianDate.IsNullable = true;
				colvarPPersianDate.IsPrimaryKey = false;
				colvarPPersianDate.IsForeignKey = false;
				colvarPPersianDate.IsReadOnly = false;
				colvarPPersianDate.DefaultSetting = @"";
				colvarPPersianDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPPersianDate);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblDoctorPool",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("PDoctorFk")]
		[Bindable(true)]
        [DataMember]
		public int? PDoctorFk 
		{
			get { return GetColumnValue<int?>(Columns.PDoctorFk); }
			set { SetColumnValue(Columns.PDoctorFk, value); }
		}
		  
		[XmlAttribute("PSaveDate")]
		[Bindable(true)]
        [DataMember]
		public DateTime? PSaveDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.PSaveDate); }
			set { SetColumnValue(Columns.PSaveDate, value); }
		}
		  
		[XmlAttribute("PName")]
		[Bindable(true)]
        [DataMember]
		public string PName 
		{
			get { return GetColumnValue<string>(Columns.PName); }
			set { SetColumnValue(Columns.PName, value); }
		}
		  
		[XmlAttribute("PTel")]
		[Bindable(true)]
        [DataMember]
		public string PTel 
		{
			get { return GetColumnValue<string>(Columns.PTel); }
			set { SetColumnValue(Columns.PTel, value); }
		}
		  
		[XmlAttribute("PStatus")]
		[Bindable(true)]
        [DataMember]
		public byte? PStatus 
		{
			get { return GetColumnValue<byte?>(Columns.PStatus); }
			set { SetColumnValue(Columns.PStatus, value); }
		}
		  
		[XmlAttribute("PDes")]
		[Bindable(true)]
        [DataMember]
		public string PDes 
		{
			get { return GetColumnValue<string>(Columns.PDes); }
			set { SetColumnValue(Columns.PDes, value); }
		}
		  
		[XmlAttribute("PPersianDate")]
		[Bindable(true)]
        [DataMember]
		public string PPersianDate 
		{
			get { return GetColumnValue<string>(Columns.PPersianDate); }
			set { SetColumnValue(Columns.PPersianDate, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varPDoctorFk,DateTime? varPSaveDate,string varPName,string varPTel,byte? varPStatus,string varPDes,string varPPersianDate)
		{
			TblDoctorPool item = new TblDoctorPool();
			
			item.PDoctorFk = varPDoctorFk;
			
			item.PSaveDate = varPSaveDate;
			
			item.PName = varPName;
			
			item.PTel = varPTel;
			
			item.PStatus = varPStatus;
			
			item.PDes = varPDes;
			
			item.PPersianDate = varPPersianDate;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int? varPDoctorFk,DateTime? varPSaveDate,string varPName,string varPTel,byte? varPStatus,string varPDes,string varPPersianDate)
		{
			TblDoctorPool item = new TblDoctorPool();
			
				item.Id = varId;
			
				item.PDoctorFk = varPDoctorFk;
			
				item.PSaveDate = varPSaveDate;
			
				item.PName = varPName;
			
				item.PTel = varPTel;
			
				item.PStatus = varPStatus;
			
				item.PDes = varPDes;
			
				item.PPersianDate = varPPersianDate;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn PDoctorFkColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn PSaveDateColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn PNameColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn PTelColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn PStatusColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn PDesColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn PPersianDateColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string PDoctorFk = @"pDoctorFk";
			 public static string PSaveDate = @"pSaveDate";
			 public static string PName = @"pName";
			 public static string PTel = @"pTel";
			 public static string PStatus = @"pStatus";
			 public static string PDes = @"pDes";
			 public static string PPersianDate = @"pPersianDate";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
