using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblDoctorPool
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblDoctorPoolController
    {
        // Preload our schema..
        TblDoctorPool thisSchemaLoad = new TblDoctorPool();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblDoctorPoolCollection FetchAll()
        {
            TblDoctorPoolCollection coll = new TblDoctorPoolCollection();
            Query qry = new Query(TblDoctorPool.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblDoctorPoolCollection FetchByID(object Id)
        {
            TblDoctorPoolCollection coll = new TblDoctorPoolCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblDoctorPoolCollection FetchByQuery(Query qry)
        {
            TblDoctorPoolCollection coll = new TblDoctorPoolCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblDoctorPool.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblDoctorPool.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? PDoctorFk,DateTime? PSaveDate,string PName,string PTel,byte? PStatus,string PDes,string PPersianDate)
	    {
		    TblDoctorPool item = new TblDoctorPool();
		    
            item.PDoctorFk = PDoctorFk;
            
            item.PSaveDate = PSaveDate;
            
            item.PName = PName;
            
            item.PTel = PTel;
            
            item.PStatus = PStatus;
            
            item.PDes = PDes;
            
            item.PPersianDate = PPersianDate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? PDoctorFk,DateTime? PSaveDate,string PName,string PTel,byte? PStatus,string PDes,string PPersianDate)
	    {
		    TblDoctorPool item = new TblDoctorPool();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.PDoctorFk = PDoctorFk;
				
			item.PSaveDate = PSaveDate;
				
			item.PName = PName;
				
			item.PTel = PTel;
				
			item.PStatus = PStatus;
				
			item.PDes = PDes;
				
			item.PPersianDate = PPersianDate;
				
	        item.Save(UserName);
	    }
    }
}
