using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblDoctors
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblDoctorController
    {
        // Preload our schema..
        TblDoctor thisSchemaLoad = new TblDoctor();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblDoctorCollection FetchAll()
        {
            TblDoctorCollection coll = new TblDoctorCollection();
            Query qry = new Query(TblDoctor.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblDoctorCollection FetchByID(object Id)
        {
            TblDoctorCollection coll = new TblDoctorCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblDoctorCollection FetchByQuery(Query qry)
        {
            TblDoctorCollection coll = new TblDoctorCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblDoctor.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblDoctor.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string DName,int? DBranchFk,string DProfileImg,string DImg,string DDes,string DInstagram,string DTelegram,string DAparat,string DEmail,string DTel,string DMobile,string DVideo,string DVideo2,string DVideo3,string DWebsite,string DSpecialty,int? DStateFk,int? DCityFk,byte? DStatus,bool? DIsDeleted,DateTime? DSaveDate,DateTime? DEndDate,string DKeyword,string DNote,string DAddress,string DWorkTime,string DLat,string DLong,string DPassword,string DUsername,string DDes2,bool? DSpecialAd,string DEnName,string DEnDes,string DArDes,string DEnSpecialty,string DArSpecialty,string DEnAddress,string DArAddress,string DEnWorkTime,string DArWorkTime,string DArName,string DWhatsapp)
	    {
		    TblDoctor item = new TblDoctor();
		    
            item.DName = DName;
            
            item.DBranchFk = DBranchFk;
            
            item.DProfileImg = DProfileImg;
            
            item.DImg = DImg;
            
            item.DDes = DDes;
            
            item.DInstagram = DInstagram;
            
            item.DTelegram = DTelegram;
            
            item.DAparat = DAparat;
            
            item.DEmail = DEmail;
            
            item.DTel = DTel;
            
            item.DMobile = DMobile;
            
            item.DVideo = DVideo;
            
            item.DVideo2 = DVideo2;
            
            item.DVideo3 = DVideo3;
            
            item.DWebsite = DWebsite;
            
            item.DSpecialty = DSpecialty;
            
            item.DStateFk = DStateFk;
            
            item.DCityFk = DCityFk;
            
            item.DStatus = DStatus;
            
            item.DIsDeleted = DIsDeleted;
            
            item.DSaveDate = DSaveDate;
            
            item.DEndDate = DEndDate;
            
            item.DKeyword = DKeyword;
            
            item.DNote = DNote;
            
            item.DAddress = DAddress;
            
            item.DWorkTime = DWorkTime;
            
            item.DLat = DLat;
            
            item.DLong = DLong;
            
            item.DPassword = DPassword;
            
            item.DUsername = DUsername;
            
            item.DDes2 = DDes2;
            
            item.DSpecialAd = DSpecialAd;
            
            item.DEnName = DEnName;
            
            item.DEnDes = DEnDes;
            
            item.DArDes = DArDes;
            
            item.DEnSpecialty = DEnSpecialty;
            
            item.DArSpecialty = DArSpecialty;
            
            item.DEnAddress = DEnAddress;
            
            item.DArAddress = DArAddress;
            
            item.DEnWorkTime = DEnWorkTime;
            
            item.DArWorkTime = DArWorkTime;
            
            item.DArName = DArName;
            
            item.DWhatsapp = DWhatsapp;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string DName,int? DBranchFk,string DProfileImg,string DImg,string DDes,string DInstagram,string DTelegram,string DAparat,string DEmail,string DTel,string DMobile,string DVideo,string DVideo2,string DVideo3,string DWebsite,string DSpecialty,int? DStateFk,int? DCityFk,byte? DStatus,bool? DIsDeleted,DateTime? DSaveDate,DateTime? DEndDate,string DKeyword,string DNote,string DAddress,string DWorkTime,string DLat,string DLong,string DPassword,string DUsername,string DDes2,bool? DSpecialAd,string DEnName,string DEnDes,string DArDes,string DEnSpecialty,string DArSpecialty,string DEnAddress,string DArAddress,string DEnWorkTime,string DArWorkTime,string DArName,string DWhatsapp)
	    {
		    TblDoctor item = new TblDoctor();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.DName = DName;
				
			item.DBranchFk = DBranchFk;
				
			item.DProfileImg = DProfileImg;
				
			item.DImg = DImg;
				
			item.DDes = DDes;
				
			item.DInstagram = DInstagram;
				
			item.DTelegram = DTelegram;
				
			item.DAparat = DAparat;
				
			item.DEmail = DEmail;
				
			item.DTel = DTel;
				
			item.DMobile = DMobile;
				
			item.DVideo = DVideo;
				
			item.DVideo2 = DVideo2;
				
			item.DVideo3 = DVideo3;
				
			item.DWebsite = DWebsite;
				
			item.DSpecialty = DSpecialty;
				
			item.DStateFk = DStateFk;
				
			item.DCityFk = DCityFk;
				
			item.DStatus = DStatus;
				
			item.DIsDeleted = DIsDeleted;
				
			item.DSaveDate = DSaveDate;
				
			item.DEndDate = DEndDate;
				
			item.DKeyword = DKeyword;
				
			item.DNote = DNote;
				
			item.DAddress = DAddress;
				
			item.DWorkTime = DWorkTime;
				
			item.DLat = DLat;
				
			item.DLong = DLong;
				
			item.DPassword = DPassword;
				
			item.DUsername = DUsername;
				
			item.DDes2 = DDes2;
				
			item.DSpecialAd = DSpecialAd;
				
			item.DEnName = DEnName;
				
			item.DEnDes = DEnDes;
				
			item.DArDes = DArDes;
				
			item.DEnSpecialty = DEnSpecialty;
				
			item.DArSpecialty = DArSpecialty;
				
			item.DEnAddress = DEnAddress;
				
			item.DArAddress = DArAddress;
				
			item.DEnWorkTime = DEnWorkTime;
				
			item.DArWorkTime = DArWorkTime;
				
			item.DArName = DArName;
				
			item.DWhatsapp = DWhatsapp;
				
	        item.Save(UserName);
	    }
    }
}
