using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblMessage class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblMessageCollection : ActiveList<TblMessage, TblMessageCollection>
	{	   
		public TblMessageCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblMessageCollection</returns>
		public TblMessageCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblMessage o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblMessage table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblMessage : ActiveRecord<TblMessage>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblMessage()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblMessage(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblMessage(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblMessage(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblMessage", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarMName = new TableSchema.TableColumn(schema);
				colvarMName.ColumnName = "mName";
				colvarMName.DataType = DbType.String;
				colvarMName.MaxLength = 50;
				colvarMName.AutoIncrement = false;
				colvarMName.IsNullable = true;
				colvarMName.IsPrimaryKey = false;
				colvarMName.IsForeignKey = false;
				colvarMName.IsReadOnly = false;
				colvarMName.DefaultSetting = @"";
				colvarMName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMName);
				
				TableSchema.TableColumn colvarMTel = new TableSchema.TableColumn(schema);
				colvarMTel.ColumnName = "mTel";
				colvarMTel.DataType = DbType.String;
				colvarMTel.MaxLength = 50;
				colvarMTel.AutoIncrement = false;
				colvarMTel.IsNullable = true;
				colvarMTel.IsPrimaryKey = false;
				colvarMTel.IsForeignKey = false;
				colvarMTel.IsReadOnly = false;
				colvarMTel.DefaultSetting = @"";
				colvarMTel.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMTel);
				
				TableSchema.TableColumn colvarMDes = new TableSchema.TableColumn(schema);
				colvarMDes.ColumnName = "mDes";
				colvarMDes.DataType = DbType.String;
				colvarMDes.MaxLength = -1;
				colvarMDes.AutoIncrement = false;
				colvarMDes.IsNullable = true;
				colvarMDes.IsPrimaryKey = false;
				colvarMDes.IsForeignKey = false;
				colvarMDes.IsReadOnly = false;
				colvarMDes.DefaultSetting = @"";
				colvarMDes.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMDes);
				
				TableSchema.TableColumn colvarMSaveDate = new TableSchema.TableColumn(schema);
				colvarMSaveDate.ColumnName = "mSaveDate";
				colvarMSaveDate.DataType = DbType.String;
				colvarMSaveDate.MaxLength = 10;
				colvarMSaveDate.AutoIncrement = false;
				colvarMSaveDate.IsNullable = true;
				colvarMSaveDate.IsPrimaryKey = false;
				colvarMSaveDate.IsForeignKey = false;
				colvarMSaveDate.IsReadOnly = false;
				colvarMSaveDate.DefaultSetting = @"";
				colvarMSaveDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMSaveDate);
				
				TableSchema.TableColumn colvarMStatus = new TableSchema.TableColumn(schema);
				colvarMStatus.ColumnName = "mStatus";
				colvarMStatus.DataType = DbType.Boolean;
				colvarMStatus.MaxLength = 0;
				colvarMStatus.AutoIncrement = false;
				colvarMStatus.IsNullable = true;
				colvarMStatus.IsPrimaryKey = false;
				colvarMStatus.IsForeignKey = false;
				colvarMStatus.IsReadOnly = false;
				colvarMStatus.DefaultSetting = @"";
				colvarMStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMStatus);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblMessage",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("MName")]
		[Bindable(true)]
        [DataMember]
		public string MName 
		{
			get { return GetColumnValue<string>(Columns.MName); }
			set { SetColumnValue(Columns.MName, value); }
		}
		  
		[XmlAttribute("MTel")]
		[Bindable(true)]
        [DataMember]
		public string MTel 
		{
			get { return GetColumnValue<string>(Columns.MTel); }
			set { SetColumnValue(Columns.MTel, value); }
		}
		  
		[XmlAttribute("MDes")]
		[Bindable(true)]
        [DataMember]
		public string MDes 
		{
			get { return GetColumnValue<string>(Columns.MDes); }
			set { SetColumnValue(Columns.MDes, value); }
		}
		  
		[XmlAttribute("MSaveDate")]
		[Bindable(true)]
        [DataMember]
		public string MSaveDate 
		{
			get { return GetColumnValue<string>(Columns.MSaveDate); }
			set { SetColumnValue(Columns.MSaveDate, value); }
		}
		  
		[XmlAttribute("MStatus")]
		[Bindable(true)]
        [DataMember]
		public bool? MStatus 
		{
			get { return GetColumnValue<bool?>(Columns.MStatus); }
			set { SetColumnValue(Columns.MStatus, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varMName,string varMTel,string varMDes,string varMSaveDate,bool? varMStatus)
		{
			TblMessage item = new TblMessage();
			
			item.MName = varMName;
			
			item.MTel = varMTel;
			
			item.MDes = varMDes;
			
			item.MSaveDate = varMSaveDate;
			
			item.MStatus = varMStatus;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varMName,string varMTel,string varMDes,string varMSaveDate,bool? varMStatus)
		{
			TblMessage item = new TblMessage();
			
				item.Id = varId;
			
				item.MName = varMName;
			
				item.MTel = varMTel;
			
				item.MDes = varMDes;
			
				item.MSaveDate = varMSaveDate;
			
				item.MStatus = varMStatus;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn MNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MTelColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MDesColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn MSaveDateColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn MStatusColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string MName = @"mName";
			 public static string MTel = @"mTel";
			 public static string MDes = @"mDes";
			 public static string MSaveDate = @"mSaveDate";
			 public static string MStatus = @"mStatus";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
