using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblPage
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblPageController
    {
        // Preload our schema..
        TblPage thisSchemaLoad = new TblPage();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblPageCollection FetchAll()
        {
            TblPageCollection coll = new TblPageCollection();
            Query qry = new Query(TblPage.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblPageCollection FetchByID(object Id)
        {
            TblPageCollection coll = new TblPageCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblPageCollection FetchByQuery(Query qry)
        {
            TblPageCollection coll = new TblPageCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblPage.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblPage.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string PPage,string PTitle,string PDes,string PKeyword)
	    {
		    TblPage item = new TblPage();
		    
            item.PPage = PPage;
            
            item.PTitle = PTitle;
            
            item.PDes = PDes;
            
            item.PKeyword = PKeyword;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string PPage,string PTitle,string PDes,string PKeyword)
	    {
		    TblPage item = new TblPage();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.PPage = PPage;
				
			item.PTitle = PTitle;
				
			item.PDes = PDes;
				
			item.PKeyword = PKeyword;
				
	        item.Save(UserName);
	    }
    }
}
