using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblPlan class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblPlanCollection : ActiveList<TblPlan, TblPlanCollection>
	{	   
		public TblPlanCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblPlanCollection</returns>
		public TblPlanCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblPlan o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblPlan table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblPlan : ActiveRecord<TblPlan>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblPlan()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblPlan(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblPlan(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblPlan(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblPlan", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarTSubject = new TableSchema.TableColumn(schema);
				colvarTSubject.ColumnName = "tSubject";
				colvarTSubject.DataType = DbType.String;
				colvarTSubject.MaxLength = 50;
				colvarTSubject.AutoIncrement = false;
				colvarTSubject.IsNullable = true;
				colvarTSubject.IsPrimaryKey = false;
				colvarTSubject.IsForeignKey = false;
				colvarTSubject.IsReadOnly = false;
				colvarTSubject.DefaultSetting = @"";
				colvarTSubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTSubject);
				
				TableSchema.TableColumn colvarTDays = new TableSchema.TableColumn(schema);
				colvarTDays.ColumnName = "tDays";
				colvarTDays.DataType = DbType.Int32;
				colvarTDays.MaxLength = 0;
				colvarTDays.AutoIncrement = false;
				colvarTDays.IsNullable = true;
				colvarTDays.IsPrimaryKey = false;
				colvarTDays.IsForeignKey = false;
				colvarTDays.IsReadOnly = false;
				colvarTDays.DefaultSetting = @"";
				colvarTDays.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTDays);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblPlan",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("TSubject")]
		[Bindable(true)]
        [DataMember]
		public string TSubject 
		{
			get { return GetColumnValue<string>(Columns.TSubject); }
			set { SetColumnValue(Columns.TSubject, value); }
		}
		  
		[XmlAttribute("TDays")]
		[Bindable(true)]
        [DataMember]
		public int? TDays 
		{
			get { return GetColumnValue<int?>(Columns.TDays); }
			set { SetColumnValue(Columns.TDays, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varTSubject,int? varTDays)
		{
			TblPlan item = new TblPlan();
			
			item.TSubject = varTSubject;
			
			item.TDays = varTDays;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varTSubject,int? varTDays)
		{
			TblPlan item = new TblPlan();
			
				item.Id = varId;
			
				item.TSubject = varTSubject;
			
				item.TDays = varTDays;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TSubjectColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn TDaysColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string TSubject = @"tSubject";
			 public static string TDays = @"tDays";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
