using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblReserve
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblReserveController
    {
        // Preload our schema..
        TblReserve thisSchemaLoad = new TblReserve();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblReserveCollection FetchAll()
        {
            TblReserveCollection coll = new TblReserveCollection();
            Query qry = new Query(TblReserve.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblReserveCollection FetchByID(object Id)
        {
            TblReserveCollection coll = new TblReserveCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblReserveCollection FetchByQuery(Query qry)
        {
            TblReserveCollection coll = new TblReserveCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblReserve.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblReserve.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? RDoctorId,string RTrackingCode,string RTime,string RPhonenumber1,string RName,DateTime? RDatetime,string RPhonenumber,DateTime? RSaveDate)
	    {
		    TblReserve item = new TblReserve();
		    
            item.RDoctorId = RDoctorId;
            
            item.RTrackingCode = RTrackingCode;
            
            item.RTime = RTime;
            
            item.RPhonenumber1 = RPhonenumber1;
            
            item.RName = RName;
            
            item.RDatetime = RDatetime;
            
            item.RPhonenumber = RPhonenumber;
            
            item.RSaveDate = RSaveDate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? RDoctorId,string RTrackingCode,string RTime,string RPhonenumber1,string RName,DateTime? RDatetime,string RPhonenumber,DateTime? RSaveDate)
	    {
		    TblReserve item = new TblReserve();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.RDoctorId = RDoctorId;
				
			item.RTrackingCode = RTrackingCode;
				
			item.RTime = RTime;
				
			item.RPhonenumber1 = RPhonenumber1;
				
			item.RName = RName;
				
			item.RDatetime = RDatetime;
				
			item.RPhonenumber = RPhonenumber;
				
			item.RSaveDate = RSaveDate;
				
	        item.Save(UserName);
	    }
    }
}
