using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblReserve class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblReserveCollection : ActiveList<TblReserve, TblReserveCollection>
	{	   
		public TblReserveCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblReserveCollection</returns>
		public TblReserveCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblReserve o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblReserve table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblReserve : ActiveRecord<TblReserve>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblReserve()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblReserve(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblReserve(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblReserve(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblReserve", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarRDoctorId = new TableSchema.TableColumn(schema);
				colvarRDoctorId.ColumnName = "rDoctorId";
				colvarRDoctorId.DataType = DbType.Int32;
				colvarRDoctorId.MaxLength = 0;
				colvarRDoctorId.AutoIncrement = false;
				colvarRDoctorId.IsNullable = true;
				colvarRDoctorId.IsPrimaryKey = false;
				colvarRDoctorId.IsForeignKey = false;
				colvarRDoctorId.IsReadOnly = false;
				colvarRDoctorId.DefaultSetting = @"";
				colvarRDoctorId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRDoctorId);
				
				TableSchema.TableColumn colvarRTrackingCode = new TableSchema.TableColumn(schema);
				colvarRTrackingCode.ColumnName = "rTrackingCode";
				colvarRTrackingCode.DataType = DbType.AnsiString;
				colvarRTrackingCode.MaxLength = 30;
				colvarRTrackingCode.AutoIncrement = false;
				colvarRTrackingCode.IsNullable = true;
				colvarRTrackingCode.IsPrimaryKey = false;
				colvarRTrackingCode.IsForeignKey = false;
				colvarRTrackingCode.IsReadOnly = false;
				colvarRTrackingCode.DefaultSetting = @"";
				colvarRTrackingCode.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRTrackingCode);
				
				TableSchema.TableColumn colvarRTime = new TableSchema.TableColumn(schema);
				colvarRTime.ColumnName = "rTime";
				colvarRTime.DataType = DbType.AnsiString;
				colvarRTime.MaxLength = 50;
				colvarRTime.AutoIncrement = false;
				colvarRTime.IsNullable = true;
				colvarRTime.IsPrimaryKey = false;
				colvarRTime.IsForeignKey = false;
				colvarRTime.IsReadOnly = false;
				colvarRTime.DefaultSetting = @"";
				colvarRTime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRTime);
				
				TableSchema.TableColumn colvarRPhonenumber1 = new TableSchema.TableColumn(schema);
				colvarRPhonenumber1.ColumnName = "rPhonenumber1";
				colvarRPhonenumber1.DataType = DbType.AnsiString;
				colvarRPhonenumber1.MaxLength = 11;
				colvarRPhonenumber1.AutoIncrement = false;
				colvarRPhonenumber1.IsNullable = true;
				colvarRPhonenumber1.IsPrimaryKey = false;
				colvarRPhonenumber1.IsForeignKey = false;
				colvarRPhonenumber1.IsReadOnly = false;
				colvarRPhonenumber1.DefaultSetting = @"";
				colvarRPhonenumber1.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRPhonenumber1);
				
				TableSchema.TableColumn colvarRName = new TableSchema.TableColumn(schema);
				colvarRName.ColumnName = "rName";
				colvarRName.DataType = DbType.String;
				colvarRName.MaxLength = 50;
				colvarRName.AutoIncrement = false;
				colvarRName.IsNullable = true;
				colvarRName.IsPrimaryKey = false;
				colvarRName.IsForeignKey = false;
				colvarRName.IsReadOnly = false;
				colvarRName.DefaultSetting = @"";
				colvarRName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRName);
				
				TableSchema.TableColumn colvarRDatetime = new TableSchema.TableColumn(schema);
				colvarRDatetime.ColumnName = "rDatetime";
				colvarRDatetime.DataType = DbType.DateTime;
				colvarRDatetime.MaxLength = 0;
				colvarRDatetime.AutoIncrement = false;
				colvarRDatetime.IsNullable = true;
				colvarRDatetime.IsPrimaryKey = false;
				colvarRDatetime.IsForeignKey = false;
				colvarRDatetime.IsReadOnly = false;
				colvarRDatetime.DefaultSetting = @"";
				colvarRDatetime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRDatetime);
				
				TableSchema.TableColumn colvarRPhonenumber = new TableSchema.TableColumn(schema);
				colvarRPhonenumber.ColumnName = "rPhonenumber";
				colvarRPhonenumber.DataType = DbType.String;
				colvarRPhonenumber.MaxLength = 11;
				colvarRPhonenumber.AutoIncrement = false;
				colvarRPhonenumber.IsNullable = true;
				colvarRPhonenumber.IsPrimaryKey = false;
				colvarRPhonenumber.IsForeignKey = false;
				colvarRPhonenumber.IsReadOnly = false;
				colvarRPhonenumber.DefaultSetting = @"";
				colvarRPhonenumber.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRPhonenumber);
				
				TableSchema.TableColumn colvarRSaveDate = new TableSchema.TableColumn(schema);
				colvarRSaveDate.ColumnName = "rSaveDate";
				colvarRSaveDate.DataType = DbType.DateTime;
				colvarRSaveDate.MaxLength = 0;
				colvarRSaveDate.AutoIncrement = false;
				colvarRSaveDate.IsNullable = true;
				colvarRSaveDate.IsPrimaryKey = false;
				colvarRSaveDate.IsForeignKey = false;
				colvarRSaveDate.IsReadOnly = false;
				colvarRSaveDate.DefaultSetting = @"";
				colvarRSaveDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRSaveDate);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblReserve",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("RDoctorId")]
		[Bindable(true)]
        [DataMember]
		public int? RDoctorId 
		{
			get { return GetColumnValue<int?>(Columns.RDoctorId); }
			set { SetColumnValue(Columns.RDoctorId, value); }
		}
		  
		[XmlAttribute("RTrackingCode")]
		[Bindable(true)]
        [DataMember]
		public string RTrackingCode 
		{
			get { return GetColumnValue<string>(Columns.RTrackingCode); }
			set { SetColumnValue(Columns.RTrackingCode, value); }
		}
		  
		[XmlAttribute("RTime")]
		[Bindable(true)]
        [DataMember]
		public string RTime 
		{
			get { return GetColumnValue<string>(Columns.RTime); }
			set { SetColumnValue(Columns.RTime, value); }
		}
		  
		[XmlAttribute("RPhonenumber1")]
		[Bindable(true)]
        [DataMember]
		public string RPhonenumber1 
		{
			get { return GetColumnValue<string>(Columns.RPhonenumber1); }
			set { SetColumnValue(Columns.RPhonenumber1, value); }
		}
		  
		[XmlAttribute("RName")]
		[Bindable(true)]
        [DataMember]
		public string RName 
		{
			get { return GetColumnValue<string>(Columns.RName); }
			set { SetColumnValue(Columns.RName, value); }
		}
		  
		[XmlAttribute("RDatetime")]
		[Bindable(true)]
        [DataMember]
		public DateTime? RDatetime 
		{
			get { return GetColumnValue<DateTime?>(Columns.RDatetime); }
			set { SetColumnValue(Columns.RDatetime, value); }
		}
		  
		[XmlAttribute("RPhonenumber")]
		[Bindable(true)]
        [DataMember]
		public string RPhonenumber 
		{
			get { return GetColumnValue<string>(Columns.RPhonenumber); }
			set { SetColumnValue(Columns.RPhonenumber, value); }
		}
		  
		[XmlAttribute("RSaveDate")]
		[Bindable(true)]
        [DataMember]
		public DateTime? RSaveDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.RSaveDate); }
			set { SetColumnValue(Columns.RSaveDate, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varRDoctorId,string varRTrackingCode,string varRTime,string varRPhonenumber1,string varRName,DateTime? varRDatetime,string varRPhonenumber,DateTime? varRSaveDate)
		{
			TblReserve item = new TblReserve();
			
			item.RDoctorId = varRDoctorId;
			
			item.RTrackingCode = varRTrackingCode;
			
			item.RTime = varRTime;
			
			item.RPhonenumber1 = varRPhonenumber1;
			
			item.RName = varRName;
			
			item.RDatetime = varRDatetime;
			
			item.RPhonenumber = varRPhonenumber;
			
			item.RSaveDate = varRSaveDate;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int? varRDoctorId,string varRTrackingCode,string varRTime,string varRPhonenumber1,string varRName,DateTime? varRDatetime,string varRPhonenumber,DateTime? varRSaveDate)
		{
			TblReserve item = new TblReserve();
			
				item.Id = varId;
			
				item.RDoctorId = varRDoctorId;
			
				item.RTrackingCode = varRTrackingCode;
			
				item.RTime = varRTime;
			
				item.RPhonenumber1 = varRPhonenumber1;
			
				item.RName = varRName;
			
				item.RDatetime = varRDatetime;
			
				item.RPhonenumber = varRPhonenumber;
			
				item.RSaveDate = varRSaveDate;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn RDoctorIdColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn RTrackingCodeColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn RTimeColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn RPhonenumber1Column
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn RNameColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn RDatetimeColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn RPhonenumberColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn RSaveDateColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string RDoctorId = @"rDoctorId";
			 public static string RTrackingCode = @"rTrackingCode";
			 public static string RTime = @"rTime";
			 public static string RPhonenumber1 = @"rPhonenumber1";
			 public static string RName = @"rName";
			 public static string RDatetime = @"rDatetime";
			 public static string RPhonenumber = @"rPhonenumber";
			 public static string RSaveDate = @"rSaveDate";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
