using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblState class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblStateCollection : ActiveList<TblState, TblStateCollection>
	{	   
		public TblStateCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblStateCollection</returns>
		public TblStateCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblState o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblState table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblState : ActiveRecord<TblState>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblState()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblState(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblState(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblState(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblState", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarSName = new TableSchema.TableColumn(schema);
				colvarSName.ColumnName = "sName";
				colvarSName.DataType = DbType.String;
				colvarSName.MaxLength = 30;
				colvarSName.AutoIncrement = false;
				colvarSName.IsNullable = true;
				colvarSName.IsPrimaryKey = false;
				colvarSName.IsForeignKey = false;
				colvarSName.IsReadOnly = false;
				colvarSName.DefaultSetting = @"";
				colvarSName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSName);
				
				TableSchema.TableColumn colvarSIsDeleted = new TableSchema.TableColumn(schema);
				colvarSIsDeleted.ColumnName = "sIsDeleted";
				colvarSIsDeleted.DataType = DbType.Boolean;
				colvarSIsDeleted.MaxLength = 0;
				colvarSIsDeleted.AutoIncrement = false;
				colvarSIsDeleted.IsNullable = true;
				colvarSIsDeleted.IsPrimaryKey = false;
				colvarSIsDeleted.IsForeignKey = false;
				colvarSIsDeleted.IsReadOnly = false;
				colvarSIsDeleted.DefaultSetting = @"";
				colvarSIsDeleted.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSIsDeleted);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblState",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("SName")]
		[Bindable(true)]
        [DataMember]
		public string SName 
		{
			get { return GetColumnValue<string>(Columns.SName); }
			set { SetColumnValue(Columns.SName, value); }
		}
		  
		[XmlAttribute("SIsDeleted")]
		[Bindable(true)]
        [DataMember]
		public bool? SIsDeleted 
		{
			get { return GetColumnValue<bool?>(Columns.SIsDeleted); }
			set { SetColumnValue(Columns.SIsDeleted, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varSName,bool? varSIsDeleted)
		{
			TblState item = new TblState();
			
			item.SName = varSName;
			
			item.SIsDeleted = varSIsDeleted;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varSName,bool? varSIsDeleted)
		{
			TblState item = new TblState();
			
				item.Id = varId;
			
				item.SName = varSName;
			
				item.SIsDeleted = varSIsDeleted;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn SNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn SIsDeletedColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string SName = @"sName";
			 public static string SIsDeleted = @"sIsDeleted";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
