using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblVideo
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblVideoController
    {
        // Preload our schema..
        TblVideo thisSchemaLoad = new TblVideo();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblVideoCollection FetchAll()
        {
            TblVideoCollection coll = new TblVideoCollection();
            Query qry = new Query(TblVideo.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblVideoCollection FetchByID(object Id)
        {
            TblVideoCollection coll = new TblVideoCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblVideoCollection FetchByQuery(Query qry)
        {
            TblVideoCollection coll = new TblVideoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblVideo.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblVideo.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string VSrc,string VSubject,int? VStateFk,byte? VStatus,byte? VLanguage)
	    {
		    TblVideo item = new TblVideo();
		    
            item.VSrc = VSrc;
            
            item.VSubject = VSubject;
            
            item.VStateFk = VStateFk;
            
            item.VStatus = VStatus;
            
            item.VLanguage = VLanguage;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string VSrc,string VSubject,int? VStateFk,byte? VStatus,byte? VLanguage)
	    {
		    TblVideo item = new TblVideo();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.VSrc = VSrc;
				
			item.VSubject = VSubject;
				
			item.VStateFk = VStateFk;
				
			item.VStatus = VStatus;
				
			item.VLanguage = VLanguage;
				
	        item.Save(UserName);
	    }
    }
}
