using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblVideo class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblVideoCollection : ActiveList<TblVideo, TblVideoCollection>
	{	   
		public TblVideoCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblVideoCollection</returns>
		public TblVideoCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblVideo o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblVideo table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblVideo : ActiveRecord<TblVideo>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblVideo()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblVideo(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblVideo(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblVideo(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblVideo", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarVSrc = new TableSchema.TableColumn(schema);
				colvarVSrc.ColumnName = "vSrc";
				colvarVSrc.DataType = DbType.String;
				colvarVSrc.MaxLength = -1;
				colvarVSrc.AutoIncrement = false;
				colvarVSrc.IsNullable = true;
				colvarVSrc.IsPrimaryKey = false;
				colvarVSrc.IsForeignKey = false;
				colvarVSrc.IsReadOnly = false;
				colvarVSrc.DefaultSetting = @"";
				colvarVSrc.ForeignKeyTableName = "";
				schema.Columns.Add(colvarVSrc);
				
				TableSchema.TableColumn colvarVSubject = new TableSchema.TableColumn(schema);
				colvarVSubject.ColumnName = "vSubject";
				colvarVSubject.DataType = DbType.String;
				colvarVSubject.MaxLength = 150;
				colvarVSubject.AutoIncrement = false;
				colvarVSubject.IsNullable = true;
				colvarVSubject.IsPrimaryKey = false;
				colvarVSubject.IsForeignKey = false;
				colvarVSubject.IsReadOnly = false;
				colvarVSubject.DefaultSetting = @"";
				colvarVSubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarVSubject);
				
				TableSchema.TableColumn colvarVStateFk = new TableSchema.TableColumn(schema);
				colvarVStateFk.ColumnName = "vStateFk";
				colvarVStateFk.DataType = DbType.Int32;
				colvarVStateFk.MaxLength = 0;
				colvarVStateFk.AutoIncrement = false;
				colvarVStateFk.IsNullable = true;
				colvarVStateFk.IsPrimaryKey = false;
				colvarVStateFk.IsForeignKey = false;
				colvarVStateFk.IsReadOnly = false;
				colvarVStateFk.DefaultSetting = @"";
				colvarVStateFk.ForeignKeyTableName = "";
				schema.Columns.Add(colvarVStateFk);
				
				TableSchema.TableColumn colvarVStatus = new TableSchema.TableColumn(schema);
				colvarVStatus.ColumnName = "vStatus";
				colvarVStatus.DataType = DbType.Byte;
				colvarVStatus.MaxLength = 0;
				colvarVStatus.AutoIncrement = false;
				colvarVStatus.IsNullable = true;
				colvarVStatus.IsPrimaryKey = false;
				colvarVStatus.IsForeignKey = false;
				colvarVStatus.IsReadOnly = false;
				colvarVStatus.DefaultSetting = @"";
				colvarVStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarVStatus);
				
				TableSchema.TableColumn colvarVLanguage = new TableSchema.TableColumn(schema);
				colvarVLanguage.ColumnName = "vLanguage";
				colvarVLanguage.DataType = DbType.Byte;
				colvarVLanguage.MaxLength = 0;
				colvarVLanguage.AutoIncrement = false;
				colvarVLanguage.IsNullable = true;
				colvarVLanguage.IsPrimaryKey = false;
				colvarVLanguage.IsForeignKey = false;
				colvarVLanguage.IsReadOnly = false;
				colvarVLanguage.DefaultSetting = @"";
				colvarVLanguage.ForeignKeyTableName = "";
				schema.Columns.Add(colvarVLanguage);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblVideo",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("VSrc")]
		[Bindable(true)]
        [DataMember]
		public string VSrc 
		{
			get { return GetColumnValue<string>(Columns.VSrc); }
			set { SetColumnValue(Columns.VSrc, value); }
		}
		  
		[XmlAttribute("VSubject")]
		[Bindable(true)]
        [DataMember]
		public string VSubject 
		{
			get { return GetColumnValue<string>(Columns.VSubject); }
			set { SetColumnValue(Columns.VSubject, value); }
		}
		  
		[XmlAttribute("VStateFk")]
		[Bindable(true)]
        [DataMember]
		public int? VStateFk 
		{
			get { return GetColumnValue<int?>(Columns.VStateFk); }
			set { SetColumnValue(Columns.VStateFk, value); }
		}
		  
		[XmlAttribute("VStatus")]
		[Bindable(true)]
        [DataMember]
		public byte? VStatus 
		{
			get { return GetColumnValue<byte?>(Columns.VStatus); }
			set { SetColumnValue(Columns.VStatus, value); }
		}
		  
		[XmlAttribute("VLanguage")]
		[Bindable(true)]
        [DataMember]
		public byte? VLanguage 
		{
			get { return GetColumnValue<byte?>(Columns.VLanguage); }
			set { SetColumnValue(Columns.VLanguage, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varVSrc,string varVSubject,int? varVStateFk,byte? varVStatus,byte? varVLanguage)
		{
			TblVideo item = new TblVideo();
			
			item.VSrc = varVSrc;
			
			item.VSubject = varVSubject;
			
			item.VStateFk = varVStateFk;
			
			item.VStatus = varVStatus;
			
			item.VLanguage = varVLanguage;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varVSrc,string varVSubject,int? varVStateFk,byte? varVStatus,byte? varVLanguage)
		{
			TblVideo item = new TblVideo();
			
				item.Id = varId;
			
				item.VSrc = varVSrc;
			
				item.VSubject = varVSubject;
			
				item.VStateFk = varVStateFk;
			
				item.VStatus = varVStatus;
			
				item.VLanguage = varVLanguage;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn VSrcColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn VSubjectColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn VStateFkColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn VStatusColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn VLanguageColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string VSrc = @"vSrc";
			 public static string VSubject = @"vSubject";
			 public static string VStateFk = @"vStateFk";
			 public static string VStatus = @"vStatus";
			 public static string VLanguage = @"vLanguage";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
